// AUTO-GENERATED by scripts/generate-dotnet-reference-catalog.mjs — do not edit by hand
// dotnet/dotnet-api-docs xml/FrameworksIndex
// generatedAt: 2026-05-25T02:36:38.348Z

export const DOTNET_API_CATALOG = {
  "generatedAt": "2026-05-25T02:36:38.348Z",
  "source": "dotnet/dotnet-api-docs xml/FrameworksIndex",
  "frameworks": {
    "net-10.0": {
      "id": "net-10.0",
      "label": ".NET 10",
      "learnIndex": "https://learn.microsoft.com/ru-ru/dotnet/api/?view=net-10.0",
      "namespaceCount": 127,
      "typeCount": 3966,
      "namespaces": [
        {
          "name": "Microsoft.CSharp.RuntimeBinder",
          "types": 6,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.csharp.runtimebinder?view=net-10.0"
        },
        {
          "name": "Microsoft.VisualBasic",
          "types": 36,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.visualbasic?view=net-10.0"
        },
        {
          "name": "Microsoft.VisualBasic.CompilerServices",
          "types": 29,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.visualbasic.compilerservices?view=net-10.0"
        },
        {
          "name": "Microsoft.VisualBasic.FileIO",
          "types": 10,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.visualbasic.fileio?view=net-10.0"
        },
        {
          "name": "Microsoft.Win32",
          "types": 8,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.win32?view=net-10.0"
        },
        {
          "name": "Microsoft.Win32.SafeHandles",
          "types": 17,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.win32.safehandles?view=net-10.0"
        },
        {
          "name": "System",
          "types": 292,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system?view=net-10.0"
        },
        {
          "name": "System.Buffers",
          "types": 20,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.buffers?view=net-10.0"
        },
        {
          "name": "System.Buffers.Binary",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.buffers.binary?view=net-10.0"
        },
        {
          "name": "System.Buffers.Text",
          "types": 4,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.buffers.text?view=net-10.0"
        },
        {
          "name": "System.CodeDom.Compiler",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.codedom.compiler?view=net-10.0"
        },
        {
          "name": "System.Collections",
          "types": 25,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.collections?view=net-10.0"
        },
        {
          "name": "System.Collections.Concurrent",
          "types": 11,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.collections.concurrent?view=net-10.0"
        },
        {
          "name": "System.Collections.Frozen",
          "types": 8,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.collections.frozen?view=net-10.0"
        },
        {
          "name": "System.Collections.Generic",
          "types": 59,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.collections.generic?view=net-10.0"
        },
        {
          "name": "System.Collections.Immutable",
          "types": 36,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.collections.immutable?view=net-10.0"
        },
        {
          "name": "System.Collections.ObjectModel",
          "types": 10,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.collections.objectmodel?view=net-10.0"
        },
        {
          "name": "System.Collections.Specialized",
          "types": 17,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.collections.specialized?view=net-10.0"
        },
        {
          "name": "System.ComponentModel",
          "types": 186,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.componentmodel?view=net-10.0"
        },
        {
          "name": "System.ComponentModel.DataAnnotations",
          "types": 39,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.componentmodel.dataannotations?view=net-10.0"
        },
        {
          "name": "System.ComponentModel.DataAnnotations.Schema",
          "types": 8,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.componentmodel.dataannotations.schema?view=net-10.0"
        },
        {
          "name": "System.ComponentModel.Design",
          "types": 60,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.componentmodel.design?view=net-10.0"
        },
        {
          "name": "System.ComponentModel.Design.Serialization",
          "types": 19,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.componentmodel.design.serialization?view=net-10.0"
        },
        {
          "name": "System.Configuration.Assemblies",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.configuration.assemblies?view=net-10.0"
        },
        {
          "name": "System.Data",
          "types": 108,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.data?view=net-10.0"
        },
        {
          "name": "System.Data.Common",
          "types": 38,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.data.common?view=net-10.0"
        },
        {
          "name": "System.Data.SqlTypes",
          "types": 24,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.data.sqltypes?view=net-10.0"
        },
        {
          "name": "System.Diagnostics",
          "types": 93,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.diagnostics?view=net-10.0"
        },
        {
          "name": "System.Diagnostics.CodeAnalysis",
          "types": 27,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.diagnostics.codeanalysis?view=net-10.0"
        },
        {
          "name": "System.Diagnostics.Contracts",
          "types": 14,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.diagnostics.contracts?view=net-10.0"
        },
        {
          "name": "System.Diagnostics.Metrics",
          "types": 18,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.diagnostics.metrics?view=net-10.0"
        },
        {
          "name": "System.Diagnostics.SymbolStore",
          "types": 15,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.diagnostics.symbolstore?view=net-10.0"
        },
        {
          "name": "System.Diagnostics.Tracing",
          "types": 32,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.diagnostics.tracing?view=net-10.0"
        },
        {
          "name": "System.Drawing",
          "types": 15,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.drawing?view=net-10.0"
        },
        {
          "name": "System.Dynamic",
          "types": 20,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.dynamic?view=net-10.0"
        },
        {
          "name": "System.Formats.Asn1",
          "types": 10,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.formats.asn1?view=net-10.0"
        },
        {
          "name": "System.Formats.Tar",
          "types": 12,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.formats.tar?view=net-10.0"
        },
        {
          "name": "System.Globalization",
          "types": 42,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.globalization?view=net-10.0"
        },
        {
          "name": "System.IO",
          "types": 56,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.io?view=net-10.0"
        },
        {
          "name": "System.IO.Compression",
          "types": 16,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.io.compression?view=net-10.0"
        },
        {
          "name": "System.IO.Enumeration",
          "types": 6,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.io.enumeration?view=net-10.0"
        },
        {
          "name": "System.IO.IsolatedStorage",
          "types": 6,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.io.isolatedstorage?view=net-10.0"
        },
        {
          "name": "System.IO.MemoryMappedFiles",
          "types": 6,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.io.memorymappedfiles?view=net-10.0"
        },
        {
          "name": "System.IO.Pipelines",
          "types": 11,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.io.pipelines?view=net-10.0"
        },
        {
          "name": "System.IO.Pipes",
          "types": 16,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.io.pipes?view=net-10.0"
        },
        {
          "name": "System.Linq",
          "types": 24,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.linq?view=net-10.0"
        },
        {
          "name": "System.Linq.Expressions",
          "types": 43,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.linq.expressions?view=net-10.0"
        },
        {
          "name": "System.Net",
          "types": 88,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.net?view=net-10.0"
        },
        {
          "name": "System.Net.Cache",
          "types": 5,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.net.cache?view=net-10.0"
        },
        {
          "name": "System.Net.Http",
          "types": 31,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.net.http?view=net-10.0"
        },
        {
          "name": "System.Net.Http.Headers",
          "types": 29,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.net.http.headers?view=net-10.0"
        },
        {
          "name": "System.Net.Http.Json",
          "types": 3,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.net.http.json?view=net-10.0"
        },
        {
          "name": "System.Net.Http.Metrics",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.net.http.metrics?view=net-10.0"
        },
        {
          "name": "System.Net.Mail",
          "types": 20,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.net.mail?view=net-10.0"
        },
        {
          "name": "System.Net.Mime",
          "types": 10,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.net.mime?view=net-10.0"
        },
        {
          "name": "System.Net.NetworkInformation",
          "types": 44,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.net.networkinformation?view=net-10.0"
        },
        {
          "name": "System.Net.Quic",
          "types": 13,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.net.quic?view=net-10.0"
        },
        {
          "name": "System.Net.Security",
          "types": 23,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.net.security?view=net-10.0"
        },
        {
          "name": "System.Net.ServerSentEvents",
          "types": 5,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.net.serversentevents?view=net-10.0"
        },
        {
          "name": "System.Net.Sockets",
          "types": 34,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.net.sockets?view=net-10.0"
        },
        {
          "name": "System.Net.WebSockets",
          "types": 16,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.net.websockets?view=net-10.0"
        },
        {
          "name": "System.Numerics",
          "types": 45,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.numerics?view=net-10.0"
        },
        {
          "name": "System.Reflection",
          "types": 105,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.reflection?view=net-10.0"
        },
        {
          "name": "System.Reflection.Emit",
          "types": 27,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.reflection.emit?view=net-10.0"
        },
        {
          "name": "System.Reflection.Metadata",
          "types": 189,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.reflection.metadata?view=net-10.0"
        },
        {
          "name": "System.Reflection.Metadata.Ecma335",
          "types": 47,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.reflection.metadata.ecma335?view=net-10.0"
        },
        {
          "name": "System.Reflection.PortableExecutable",
          "types": 28,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.reflection.portableexecutable?view=net-10.0"
        },
        {
          "name": "System.Resources",
          "types": 11,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.resources?view=net-10.0"
        },
        {
          "name": "System.Runtime",
          "types": 11,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.runtime?view=net-10.0"
        },
        {
          "name": "System.Runtime.CompilerServices",
          "types": 165,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.runtime.compilerservices?view=net-10.0"
        },
        {
          "name": "System.Runtime.ConstrainedExecution",
          "types": 5,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.runtime.constrainedexecution?view=net-10.0"
        },
        {
          "name": "System.Runtime.ExceptionServices",
          "types": 4,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.runtime.exceptionservices?view=net-10.0"
        },
        {
          "name": "System.Runtime.InteropServices",
          "types": 125,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.runtime.interopservices?view=net-10.0"
        },
        {
          "name": "System.Runtime.InteropServices.ComTypes",
          "types": 59,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.runtime.interopservices.comtypes?view=net-10.0"
        },
        {
          "name": "System.Runtime.InteropServices.Java",
          "types": 4,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.runtime.interopservices.java?view=net-10.0"
        },
        {
          "name": "System.Runtime.InteropServices.JavaScript",
          "types": 30,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.runtime.interopservices.javascript?view=net-10.0"
        },
        {
          "name": "System.Runtime.InteropServices.Marshalling",
          "types": 53,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.runtime.interopservices.marshalling?view=net-10.0"
        },
        {
          "name": "System.Runtime.InteropServices.ObjectiveC",
          "types": 4,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.runtime.interopservices.objectivec?view=net-10.0"
        },
        {
          "name": "System.Runtime.InteropServices.Swift",
          "types": 4,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.runtime.interopservices.swift?view=net-10.0"
        },
        {
          "name": "System.Runtime.Intrinsics",
          "types": 8,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.runtime.intrinsics?view=net-10.0"
        },
        {
          "name": "System.Runtime.Intrinsics.Arm",
          "types": 22,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.runtime.intrinsics.arm?view=net-10.0"
        },
        {
          "name": "System.Runtime.Intrinsics.Wasm",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.runtime.intrinsics.wasm?view=net-10.0"
        },
        {
          "name": "System.Runtime.Intrinsics.X86",
          "types": 76,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.runtime.intrinsics.x86?view=net-10.0"
        },
        {
          "name": "System.Runtime.Loader",
          "types": 3,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.runtime.loader?view=net-10.0"
        },
        {
          "name": "System.Runtime.Remoting",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.runtime.remoting?view=net-10.0"
        },
        {
          "name": "System.Runtime.Serialization",
          "types": 51,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.runtime.serialization?view=net-10.0"
        },
        {
          "name": "System.Runtime.Serialization.DataContracts",
          "types": 4,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.runtime.serialization.datacontracts?view=net-10.0"
        },
        {
          "name": "System.Runtime.Serialization.Formatters",
          "types": 4,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.runtime.serialization.formatters?view=net-10.0"
        },
        {
          "name": "System.Runtime.Serialization.Formatters.Binary",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.runtime.serialization.formatters.binary?view=net-10.0"
        },
        {
          "name": "System.Runtime.Serialization.Json",
          "types": 5,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.runtime.serialization.json?view=net-10.0"
        },
        {
          "name": "System.Runtime.Versioning",
          "types": 16,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.runtime.versioning?view=net-10.0"
        },
        {
          "name": "System.Security",
          "types": 20,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.security?view=net-10.0"
        },
        {
          "name": "System.Security.AccessControl",
          "types": 68,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.security.accesscontrol?view=net-10.0"
        },
        {
          "name": "System.Security.Authentication",
          "types": 6,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.security.authentication?view=net-10.0"
        },
        {
          "name": "System.Security.Authentication.ExtendedProtection",
          "types": 7,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.security.authentication.extendedprotection?view=net-10.0"
        },
        {
          "name": "System.Security.Claims",
          "types": 5,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.security.claims?view=net-10.0"
        },
        {
          "name": "System.Security.Cryptography",
          "types": 169,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.security.cryptography?view=net-10.0"
        },
        {
          "name": "System.Security.Cryptography.X509Certificates",
          "types": 56,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.security.cryptography.x509certificates?view=net-10.0"
        },
        {
          "name": "System.Security.Permissions",
          "types": 6,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.security.permissions?view=net-10.0"
        },
        {
          "name": "System.Security.Policy",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.security.policy?view=net-10.0"
        },
        {
          "name": "System.Security.Principal",
          "types": 17,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.security.principal?view=net-10.0"
        },
        {
          "name": "System.Text",
          "types": 36,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.text?view=net-10.0"
        },
        {
          "name": "System.Text.Encodings.Web",
          "types": 5,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.text.encodings.web?view=net-10.0"
        },
        {
          "name": "System.Text.Json",
          "types": 20,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.text.json?view=net-10.0"
        },
        {
          "name": "System.Text.Json.Nodes",
          "types": 5,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.text.json.nodes?view=net-10.0"
        },
        {
          "name": "System.Text.Json.Schema",
          "types": 3,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.text.json.schema?view=net-10.0"
        },
        {
          "name": "System.Text.Json.Serialization",
          "types": 40,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.text.json.serialization?view=net-10.0"
        },
        {
          "name": "System.Text.Json.Serialization.Metadata",
          "types": 15,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.text.json.serialization.metadata?view=net-10.0"
        },
        {
          "name": "System.Text.RegularExpressions",
          "types": 19,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.text.regularexpressions?view=net-10.0"
        },
        {
          "name": "System.Text.Unicode",
          "types": 4,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.text.unicode?view=net-10.0"
        },
        {
          "name": "System.Threading",
          "types": 77,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.threading?view=net-10.0"
        },
        {
          "name": "System.Threading.Channels",
          "types": 11,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.threading.channels?view=net-10.0"
        },
        {
          "name": "System.Threading.Tasks",
          "types": 24,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.threading.tasks?view=net-10.0"
        },
        {
          "name": "System.Threading.Tasks.Dataflow",
          "types": 23,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.threading.tasks.dataflow?view=net-10.0"
        },
        {
          "name": "System.Threading.Tasks.Sources",
          "types": 5,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.threading.tasks.sources?view=net-10.0"
        },
        {
          "name": "System.Timers",
          "types": 4,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.timers?view=net-10.0"
        },
        {
          "name": "System.Transactions",
          "types": 34,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.transactions?view=net-10.0"
        },
        {
          "name": "System.Web",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.web?view=net-10.0"
        },
        {
          "name": "System.Windows.Input",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.windows.input?view=net-10.0"
        },
        {
          "name": "System.Windows.Markup",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.windows.markup?view=net-10.0"
        },
        {
          "name": "System.Xml",
          "types": 82,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.xml?view=net-10.0"
        },
        {
          "name": "System.Xml.Linq",
          "types": 23,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.xml.linq?view=net-10.0"
        },
        {
          "name": "System.Xml.Resolvers",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.xml.resolvers?view=net-10.0"
        },
        {
          "name": "System.Xml.Schema",
          "types": 89,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.xml.schema?view=net-10.0"
        },
        {
          "name": "System.Xml.Serialization",
          "types": 72,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.xml.serialization?view=net-10.0"
        },
        {
          "name": "System.Xml.XPath",
          "types": 15,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.xml.xpath?view=net-10.0"
        },
        {
          "name": "System.Xml.Xsl",
          "types": 11,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.xml.xsl?view=net-10.0"
        }
      ]
    },
    "netframework-4.8": {
      "id": "netframework-4.8",
      "label": ".NET Framework 4.8",
      "learnIndex": "https://learn.microsoft.com/ru-ru/dotnet/api/?view=netframework-4.8&preserve-view=true",
      "namespaceCount": 141,
      "typeCount": 1701,
      "namespaces": [
        {
          "name": "Microsoft.DotNet.PlatformAbstractions",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.dotnet.platformabstractions?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.AI",
          "types": 235,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.ai?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.AI.Evaluation",
          "types": 19,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.ai.evaluation?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.AI.Evaluation.NLP",
          "types": 6,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.ai.evaluation.nlp?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.AI.Evaluation.Quality",
          "types": 18,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.ai.evaluation.quality?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.AI.Evaluation.Reporting",
          "types": 12,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.ai.evaluation.reporting?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.AI.Evaluation.Reporting.Formats.Html",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.ai.evaluation.reporting.formats.html?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.AI.Evaluation.Reporting.Formats.Json",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.ai.evaluation.reporting.formats.json?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.AI.Evaluation.Reporting.Storage",
          "types": 6,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.ai.evaluation.reporting.storage?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.AI.Evaluation.Safety",
          "types": 15,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.ai.evaluation.safety?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.AmbientMetadata",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.ambientmetadata?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.AsyncState",
          "types": 4,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.asyncstate?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Caching.Distributed",
          "types": 6,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.caching.distributed?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Caching.Hybrid",
          "types": 7,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.caching.hybrid?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Caching.Memory",
          "types": 14,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.caching.memory?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Caching.SqlServer",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.caching.sqlserver?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Caching.StackExchangeRedis",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.caching.stackexchangeredis?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Compliance.Redaction",
          "types": 5,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.compliance.redaction?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Compliance.Testing",
          "types": 9,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.compliance.testing?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Configuration",
          "types": 40,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.configuration?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Configuration.CommandLine",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.configuration.commandline?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Configuration.EnvironmentVariables",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.configuration.environmentvariables?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Configuration.Ini",
          "types": 4,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.configuration.ini?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Configuration.Json",
          "types": 4,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.configuration.json?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Configuration.KeyPerFile",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.configuration.keyperfile?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Configuration.Memory",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.configuration.memory?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Configuration.UserSecrets",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.configuration.usersecrets?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Configuration.Xml",
          "types": 5,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.configuration.xml?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.DataIngestion",
          "types": 30,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.dataingestion?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.DataIngestion.Chunkers",
          "types": 3,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.dataingestion.chunkers?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.DependencyInjection",
          "types": 82,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.dependencyinjection?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.DependencyInjection.Extensions",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.dependencyinjection.extensions?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.DependencyModel",
          "types": 17,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.dependencymodel?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.DependencyModel.Resolution",
          "types": 6,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.dependencymodel.resolution?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Diagnostics.Enrichment",
          "types": 7,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.diagnostics.enrichment?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Diagnostics.ExceptionSummarization",
          "types": 5,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.diagnostics.exceptionsummarization?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Diagnostics.HealthChecks",
          "types": 16,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.diagnostics.healthchecks?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Diagnostics.Latency",
          "types": 14,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.diagnostics.latency?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Diagnostics.Metrics",
          "types": 18,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.diagnostics.metrics?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Diagnostics.Metrics.Configuration",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.diagnostics.metrics.configuration?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Diagnostics.Metrics.Testing",
          "types": 3,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.diagnostics.metrics.testing?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Diagnostics.Probes",
          "types": 3,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.diagnostics.probes?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Diagnostics.ResourceMonitoring",
          "types": 11,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.diagnostics.resourcemonitoring?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Diagnostics.Sampling",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.diagnostics.sampling?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.FileProviders",
          "types": 11,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.fileproviders?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.FileProviders.Composite",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.fileproviders.composite?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.FileProviders.Embedded",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.fileproviders.embedded?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.FileProviders.Internal",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.fileproviders.internal?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.FileProviders.Physical",
          "types": 6,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.fileproviders.physical?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.FileSystemGlobbing",
          "types": 5,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.filesystemglobbing?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.FileSystemGlobbing.Abstractions",
          "types": 5,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.filesystemglobbing.abstractions?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.FileSystemGlobbing.Internal",
          "types": 7,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.filesystemglobbing.internal?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.FileSystemGlobbing.Internal.PathSegments",
          "types": 5,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.filesystemglobbing.internal.pathsegments?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.FileSystemGlobbing.Internal.PatternContexts",
          "types": 9,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.filesystemglobbing.internal.patterncontexts?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.FileSystemGlobbing.Internal.Patterns",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.filesystemglobbing.internal.patterns?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Hosting",
          "types": 32,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.hosting?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Hosting.Internal",
          "types": 3,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.hosting.internal?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Hosting.Testing",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.hosting.testing?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Hosting.WindowsServices",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.hosting.windowsservices?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Http",
          "types": 4,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.http?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Http.Diagnostics",
          "types": 6,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.http.diagnostics?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Http.Latency",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.http.latency?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Http.Logging",
          "types": 8,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.http.logging?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Http.Resilience",
          "types": 28,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.http.resilience?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Internal",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.internal?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Localization",
          "types": 13,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.localization?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Logging",
          "types": 45,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.logging?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Logging.Abstractions",
          "types": 7,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.logging.abstractions?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Logging.Abstractions.Internal",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.logging.abstractions.internal?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Logging.AzureAppServices",
          "types": 7,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.logging.azureappservices?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Logging.Configuration",
          "types": 5,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.logging.configuration?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Logging.Console",
          "types": 13,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.logging.console?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Logging.Debug",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.logging.debug?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Logging.EventLog",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.logging.eventlog?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Logging.EventSource",
          "types": 3,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.logging.eventsource?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Logging.Internal",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.logging.internal?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Logging.Testing",
          "types": 6,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.logging.testing?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Logging.TraceSource",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.logging.tracesource?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.ObjectPool",
          "types": 14,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.objectpool?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Options",
          "types": 48,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.options?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Options.Contextual",
          "types": 4,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.options.contextual?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Options.Contextual.Provider",
          "types": 4,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.options.contextual.provider?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Primitives",
          "types": 12,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.primitives?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Time.Testing",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.time.testing?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.VectorData",
          "types": 29,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.vectordata?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.VectorData.ProviderServices",
          "types": 12,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.vectordata.providerservices?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.VectorData.ProviderServices.Filter",
          "types": 3,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.vectordata.providerservices.filter?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.WebEncoders",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.webencoders?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.WebEncoders.Testing",
          "types": 3,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.webencoders.testing?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Microsoft.Win32",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.win32?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "OpenAI.Assistants",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/openai.assistants?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "OpenAI.Chat",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/openai.chat?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "OpenAI.Realtime",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/openai.realtime?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "OpenAI.Responses",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/openai.responses?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "Polly",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/polly?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System",
          "types": 8,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Buffers.Text",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.buffers.text?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Collections.Frozen",
          "types": 6,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.collections.frozen?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Collections.Generic",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.collections.generic?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Collections.Immutable",
          "types": 36,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.collections.immutable?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Composition",
          "types": 17,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.composition?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Composition.Convention",
          "types": 7,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.composition.convention?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Composition.Hosting",
          "types": 3,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.composition.hosting?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Composition.Hosting.Core",
          "types": 9,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.composition.hosting.core?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Diagnostics",
          "types": 28,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.diagnostics?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Diagnostics.Metrics",
          "types": 18,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.diagnostics.metrics?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Formats.Asn1",
          "types": 11,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.formats.asn1?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Formats.Cbor",
          "types": 7,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.formats.cbor?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Formats.Nrbf",
          "types": 10,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.formats.nrbf?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.IO.Hashing",
          "types": 10,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.io.hashing?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.IO.Pipelines",
          "types": 11,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.io.pipelines?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Linq",
          "types": 3,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.linq?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Net",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.net?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Net.Http",
          "types": 9,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.net.http?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Net.Http.Json",
          "types": 3,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.net.http.json?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Net.ServerSentEvents",
          "types": 5,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.net.serversentevents?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Numerics.Tensors",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.numerics.tensors?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Reflection",
          "types": 9,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.reflection?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Reflection.Metadata",
          "types": 186,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.reflection.metadata?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Reflection.Metadata.Ecma335",
          "types": 47,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.reflection.metadata.ecma335?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Reflection.PortableExecutable",
          "types": 28,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.reflection.portableexecutable?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Resources.Extensions",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.resources.extensions?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Runtime.CompilerServices",
          "types": 6,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.runtime.compilerservices?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Runtime.InteropServices",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.runtime.interopservices?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Security.Cryptography",
          "types": 17,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.security.cryptography?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Security.Cryptography.Cose",
          "types": 9,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.security.cryptography.cose?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Security.Cryptography.X509Certificates",
          "types": 4,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.security.cryptography.x509certificates?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Text",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.text?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Text.Encodings.Web",
          "types": 5,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.text.encodings.web?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Text.Json",
          "types": 20,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.text.json?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Text.Json.Nodes",
          "types": 5,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.text.json.nodes?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Text.Json.Schema",
          "types": 3,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.text.json.schema?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Text.Json.Serialization",
          "types": 42,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.text.json.serialization?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Text.Json.Serialization.Metadata",
          "types": 15,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.text.json.serialization.metadata?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Text.Unicode",
          "types": 3,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.text.unicode?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Threading",
          "types": 5,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.threading?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Threading.Channels",
          "types": 10,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.threading.channels?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Threading.RateLimiting",
          "types": 19,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.threading.ratelimiting?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Threading.Tasks",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.threading.tasks?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Threading.Tasks.Dataflow",
          "types": 23,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.threading.tasks.dataflow?view=netframework-4.8&preserve-view=true"
        },
        {
          "name": "System.Threading.Tasks.Sources",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.threading.tasks.sources?view=netframework-4.8&preserve-view=true"
        }
      ]
    },
    "netframework-4.8.1": {
      "id": "netframework-4.8.1",
      "label": ".NET Framework 4.8.1",
      "learnIndex": "https://learn.microsoft.com/ru-ru/dotnet/api/?view=netframework-4.8.1&preserve-view=true",
      "namespaceCount": 141,
      "typeCount": 1701,
      "namespaces": [
        {
          "name": "Microsoft.DotNet.PlatformAbstractions",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.dotnet.platformabstractions?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.AI",
          "types": 235,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.ai?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.AI.Evaluation",
          "types": 19,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.ai.evaluation?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.AI.Evaluation.NLP",
          "types": 6,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.ai.evaluation.nlp?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.AI.Evaluation.Quality",
          "types": 18,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.ai.evaluation.quality?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.AI.Evaluation.Reporting",
          "types": 12,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.ai.evaluation.reporting?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.AI.Evaluation.Reporting.Formats.Html",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.ai.evaluation.reporting.formats.html?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.AI.Evaluation.Reporting.Formats.Json",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.ai.evaluation.reporting.formats.json?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.AI.Evaluation.Reporting.Storage",
          "types": 6,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.ai.evaluation.reporting.storage?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.AI.Evaluation.Safety",
          "types": 15,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.ai.evaluation.safety?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.AmbientMetadata",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.ambientmetadata?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.AsyncState",
          "types": 4,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.asyncstate?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Caching.Distributed",
          "types": 6,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.caching.distributed?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Caching.Hybrid",
          "types": 7,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.caching.hybrid?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Caching.Memory",
          "types": 14,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.caching.memory?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Caching.SqlServer",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.caching.sqlserver?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Caching.StackExchangeRedis",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.caching.stackexchangeredis?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Compliance.Redaction",
          "types": 5,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.compliance.redaction?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Compliance.Testing",
          "types": 9,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.compliance.testing?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Configuration",
          "types": 40,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.configuration?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Configuration.CommandLine",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.configuration.commandline?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Configuration.EnvironmentVariables",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.configuration.environmentvariables?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Configuration.Ini",
          "types": 4,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.configuration.ini?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Configuration.Json",
          "types": 4,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.configuration.json?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Configuration.KeyPerFile",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.configuration.keyperfile?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Configuration.Memory",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.configuration.memory?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Configuration.UserSecrets",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.configuration.usersecrets?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Configuration.Xml",
          "types": 5,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.configuration.xml?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.DataIngestion",
          "types": 30,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.dataingestion?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.DataIngestion.Chunkers",
          "types": 3,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.dataingestion.chunkers?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.DependencyInjection",
          "types": 82,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.dependencyinjection?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.DependencyInjection.Extensions",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.dependencyinjection.extensions?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.DependencyModel",
          "types": 17,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.dependencymodel?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.DependencyModel.Resolution",
          "types": 6,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.dependencymodel.resolution?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Diagnostics.Enrichment",
          "types": 7,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.diagnostics.enrichment?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Diagnostics.ExceptionSummarization",
          "types": 5,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.diagnostics.exceptionsummarization?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Diagnostics.HealthChecks",
          "types": 16,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.diagnostics.healthchecks?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Diagnostics.Latency",
          "types": 14,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.diagnostics.latency?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Diagnostics.Metrics",
          "types": 18,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.diagnostics.metrics?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Diagnostics.Metrics.Configuration",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.diagnostics.metrics.configuration?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Diagnostics.Metrics.Testing",
          "types": 3,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.diagnostics.metrics.testing?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Diagnostics.Probes",
          "types": 3,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.diagnostics.probes?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Diagnostics.ResourceMonitoring",
          "types": 11,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.diagnostics.resourcemonitoring?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Diagnostics.Sampling",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.diagnostics.sampling?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.FileProviders",
          "types": 11,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.fileproviders?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.FileProviders.Composite",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.fileproviders.composite?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.FileProviders.Embedded",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.fileproviders.embedded?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.FileProviders.Internal",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.fileproviders.internal?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.FileProviders.Physical",
          "types": 6,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.fileproviders.physical?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.FileSystemGlobbing",
          "types": 5,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.filesystemglobbing?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.FileSystemGlobbing.Abstractions",
          "types": 5,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.filesystemglobbing.abstractions?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.FileSystemGlobbing.Internal",
          "types": 7,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.filesystemglobbing.internal?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.FileSystemGlobbing.Internal.PathSegments",
          "types": 5,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.filesystemglobbing.internal.pathsegments?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.FileSystemGlobbing.Internal.PatternContexts",
          "types": 9,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.filesystemglobbing.internal.patterncontexts?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.FileSystemGlobbing.Internal.Patterns",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.filesystemglobbing.internal.patterns?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Hosting",
          "types": 32,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.hosting?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Hosting.Internal",
          "types": 3,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.hosting.internal?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Hosting.Testing",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.hosting.testing?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Hosting.WindowsServices",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.hosting.windowsservices?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Http",
          "types": 4,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.http?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Http.Diagnostics",
          "types": 6,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.http.diagnostics?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Http.Latency",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.http.latency?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Http.Logging",
          "types": 8,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.http.logging?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Http.Resilience",
          "types": 28,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.http.resilience?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Internal",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.internal?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Localization",
          "types": 13,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.localization?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Logging",
          "types": 45,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.logging?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Logging.Abstractions",
          "types": 7,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.logging.abstractions?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Logging.Abstractions.Internal",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.logging.abstractions.internal?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Logging.AzureAppServices",
          "types": 7,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.logging.azureappservices?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Logging.Configuration",
          "types": 5,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.logging.configuration?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Logging.Console",
          "types": 13,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.logging.console?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Logging.Debug",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.logging.debug?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Logging.EventLog",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.logging.eventlog?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Logging.EventSource",
          "types": 3,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.logging.eventsource?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Logging.Internal",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.logging.internal?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Logging.Testing",
          "types": 6,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.logging.testing?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Logging.TraceSource",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.logging.tracesource?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.ObjectPool",
          "types": 14,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.objectpool?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Options",
          "types": 48,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.options?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Options.Contextual",
          "types": 4,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.options.contextual?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Options.Contextual.Provider",
          "types": 4,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.options.contextual.provider?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Primitives",
          "types": 12,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.primitives?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.Time.Testing",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.time.testing?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.VectorData",
          "types": 29,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.vectordata?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.VectorData.ProviderServices",
          "types": 12,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.vectordata.providerservices?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.VectorData.ProviderServices.Filter",
          "types": 3,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.vectordata.providerservices.filter?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.WebEncoders",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.webencoders?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Extensions.WebEncoders.Testing",
          "types": 3,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.extensions.webencoders.testing?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Microsoft.Win32",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/microsoft.win32?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "OpenAI.Assistants",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/openai.assistants?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "OpenAI.Chat",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/openai.chat?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "OpenAI.Realtime",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/openai.realtime?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "OpenAI.Responses",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/openai.responses?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "Polly",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/polly?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System",
          "types": 8,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Buffers.Text",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.buffers.text?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Collections.Frozen",
          "types": 6,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.collections.frozen?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Collections.Generic",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.collections.generic?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Collections.Immutable",
          "types": 36,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.collections.immutable?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Composition",
          "types": 17,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.composition?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Composition.Convention",
          "types": 7,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.composition.convention?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Composition.Hosting",
          "types": 3,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.composition.hosting?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Composition.Hosting.Core",
          "types": 9,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.composition.hosting.core?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Diagnostics",
          "types": 28,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.diagnostics?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Diagnostics.Metrics",
          "types": 18,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.diagnostics.metrics?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Formats.Asn1",
          "types": 11,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.formats.asn1?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Formats.Cbor",
          "types": 7,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.formats.cbor?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Formats.Nrbf",
          "types": 10,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.formats.nrbf?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.IO.Hashing",
          "types": 10,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.io.hashing?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.IO.Pipelines",
          "types": 11,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.io.pipelines?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Linq",
          "types": 3,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.linq?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Net",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.net?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Net.Http",
          "types": 9,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.net.http?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Net.Http.Json",
          "types": 3,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.net.http.json?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Net.ServerSentEvents",
          "types": 5,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.net.serversentevents?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Numerics.Tensors",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.numerics.tensors?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Reflection",
          "types": 9,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.reflection?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Reflection.Metadata",
          "types": 186,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.reflection.metadata?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Reflection.Metadata.Ecma335",
          "types": 47,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.reflection.metadata.ecma335?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Reflection.PortableExecutable",
          "types": 28,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.reflection.portableexecutable?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Resources.Extensions",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.resources.extensions?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Runtime.CompilerServices",
          "types": 6,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.runtime.compilerservices?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Runtime.InteropServices",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.runtime.interopservices?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Security.Cryptography",
          "types": 17,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.security.cryptography?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Security.Cryptography.Cose",
          "types": 9,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.security.cryptography.cose?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Security.Cryptography.X509Certificates",
          "types": 4,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.security.cryptography.x509certificates?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Text",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.text?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Text.Encodings.Web",
          "types": 5,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.text.encodings.web?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Text.Json",
          "types": 20,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.text.json?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Text.Json.Nodes",
          "types": 5,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.text.json.nodes?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Text.Json.Schema",
          "types": 3,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.text.json.schema?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Text.Json.Serialization",
          "types": 42,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.text.json.serialization?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Text.Json.Serialization.Metadata",
          "types": 15,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.text.json.serialization.metadata?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Text.Unicode",
          "types": 3,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.text.unicode?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Threading",
          "types": 5,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.threading?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Threading.Channels",
          "types": 10,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.threading.channels?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Threading.RateLimiting",
          "types": 19,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.threading.ratelimiting?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Threading.Tasks",
          "types": 2,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.threading.tasks?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Threading.Tasks.Dataflow",
          "types": 23,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.threading.tasks.dataflow?view=netframework-4.8.1&preserve-view=true"
        },
        {
          "name": "System.Threading.Tasks.Sources",
          "types": 1,
          "url": "https://learn.microsoft.com/ru-ru/dotnet/api/system.threading.tasks.sources?view=netframework-4.8.1&preserve-view=true"
        }
      ]
    }
  }
};
