// AUTO-GENERATED by scripts/generate-dotnet-reference-catalog.mjs — do not edit by hand
// learn.microsoft.com ru-ru/dotnet/fsharp/language-reference/ (index.md)
// generatedAt: 2026-05-25T02:36:38.801Z

export const FSHARP_LANGUAGE_REF_CATALOG = {
  "generatedAt": "2026-05-25T02:36:38.801Z",
  "source": "learn.microsoft.com ru-ru/dotnet/fsharp/language-reference/ (index.md)",
  "learnIndex": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/",
  "entryCount": 77,
  "entries": [
    {
      "id": "/dotnet/fsharp/language-reference/namespaces",
      "title": "Пространства имён",
      "trail": "Упорядочение кода",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/namespaces"
    },
    {
      "id": "/dotnet/fsharp/language-reference/modules",
      "title": "Модули",
      "trail": "Упорядочение кода",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/modules"
    },
    {
      "id": "/dotnet/fsharp/language-reference/import-declarations-the-open-keyword",
      "title": "Объявления open",
      "trail": "Упорядочение кода",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/import-declarations-the-open-keyword"
    },
    {
      "id": "/dotnet/fsharp/language-reference/signature-files",
      "title": "Файлы подписей",
      "trail": "Упорядочение кода",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/signature-files"
    },
    {
      "id": "/dotnet/fsharp/language-reference/access-control",
      "title": "Контроль доступа",
      "trail": "Упорядочение кода",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/access-control"
    },
    {
      "id": "/dotnet/fsharp/language-reference/xml-documentation",
      "title": "XML-документация",
      "trail": "Упорядочение кода",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/xml-documentation"
    },
    {
      "id": "/dotnet/fsharp/language-reference/literals",
      "title": "Литералы",
      "trail": "Литералы и строки",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/literals"
    },
    {
      "id": "/dotnet/fsharp/language-reference/strings",
      "title": "Строки",
      "trail": "Литералы и строки",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/strings"
    },
    {
      "id": "/dotnet/fsharp/language-reference/interpolated-strings",
      "title": "Интерполированные строки",
      "trail": "Литералы и строки",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/interpolated-strings"
    },
    {
      "id": "/dotnet/fsharp/language-reference/values/",
      "title": "Значения",
      "trail": "Значения и функции",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/values/"
    },
    {
      "id": "/dotnet/fsharp/language-reference/functions/",
      "title": "Функции",
      "trail": "Значения и функции",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/functions/"
    },
    {
      "id": "/dotnet/fsharp/language-reference/functions/lambda-expressions-the-fun-keyword",
      "title": "Лямбда-выражения (fun)",
      "trail": "Значения и функции",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/functions/lambda-expressions-the-fun-keyword"
    },
    {
      "id": "/dotnet/fsharp/language-reference/conditional-expressions-if-then-else",
      "title": "if...then...else",
      "trail": "Циклы и условия",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/conditional-expressions-if-then-else"
    },
    {
      "id": "/dotnet/fsharp/language-reference/loops-for-in-expression",
      "title": "for...in",
      "trail": "Циклы и условия",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/loops-for-in-expression"
    },
    {
      "id": "/dotnet/fsharp/language-reference/loops-for-to-expression",
      "title": "for...to",
      "trail": "Циклы и условия",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/loops-for-to-expression"
    },
    {
      "id": "/dotnet/fsharp/language-reference/loops-while-do-expression",
      "title": "while...do",
      "trail": "Циклы и условия",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/loops-while-do-expression"
    },
    {
      "id": "/dotnet/fsharp/language-reference/pattern-matching",
      "title": "Шаблоны",
      "trail": "Сопоставление с образцом",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/pattern-matching"
    },
    {
      "id": "/dotnet/fsharp/language-reference/match-expressions",
      "title": "match",
      "trail": "Сопоставление с образцом",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/match-expressions"
    },
    {
      "id": "/dotnet/fsharp/language-reference/active-patterns",
      "title": "Активные шаблоны",
      "trail": "Сопоставление с образцом",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/active-patterns"
    },
    {
      "id": "/dotnet/fsharp/language-reference/exception-handling/",
      "title": "Обзор",
      "trail": "Обработка исключений",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/exception-handling/"
    },
    {
      "id": "/dotnet/fsharp/language-reference/exception-handling/the-try-with-expression",
      "title": "try...with",
      "trail": "Обработка исключений",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/exception-handling/the-try-with-expression"
    },
    {
      "id": "/dotnet/fsharp/language-reference/exception-handling/the-try-finally-expression",
      "title": "try...finally",
      "trail": "Обработка исключений",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/exception-handling/the-try-finally-expression"
    },
    {
      "id": "/dotnet/fsharp/language-reference/resource-management-the-use-keyword",
      "title": "use / using",
      "trail": "Обработка исключений",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/resource-management-the-use-keyword"
    },
    {
      "id": "/dotnet/fsharp/language-reference/assertions",
      "title": "assert",
      "trail": "Обработка исключений",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/assertions"
    },
    {
      "id": "/dotnet/fsharp/language-reference/fsharp-types",
      "title": "Типы F#",
      "trail": "Типы и вывод типов",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/fsharp-types"
    },
    {
      "id": "/dotnet/fsharp/language-reference/basic-types",
      "title": "Базовые типы",
      "trail": "Типы и вывод типов",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/basic-types"
    },
    {
      "id": "/dotnet/fsharp/language-reference/unit-type",
      "title": "Тип unit",
      "trail": "Типы и вывод типов",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/unit-type"
    },
    {
      "id": "/dotnet/fsharp/language-reference/type-abbreviations",
      "title": "Сокращения типов",
      "trail": "Типы и вывод типов",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/type-abbreviations"
    },
    {
      "id": "/dotnet/fsharp/language-reference/type-inference",
      "title": "Вывод типов",
      "trail": "Типы и вывод типов",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/type-inference"
    },
    {
      "id": "/dotnet/fsharp/language-reference/casting-and-conversions",
      "title": "Приведение и преобразование",
      "trail": "Типы и вывод типов",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/casting-and-conversions"
    },
    {
      "id": "/dotnet/fsharp/language-reference/generics/",
      "title": "Обобщения",
      "trail": "Типы и вывод типов",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/generics/"
    },
    {
      "id": "/dotnet/fsharp/language-reference/generics/automatic-generalization",
      "title": "Автообобщение",
      "trail": "Типы и вывод типов",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/generics/automatic-generalization"
    },
    {
      "id": "/dotnet/fsharp/language-reference/generics/constraints",
      "title": "Ограничения generics",
      "trail": "Типы и вывод типов",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/generics/constraints"
    },
    {
      "id": "/dotnet/fsharp/language-reference/flexible-types",
      "title": "Гибкие типы",
      "trail": "Типы и вывод типов",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/flexible-types"
    },
    {
      "id": "/dotnet/fsharp/language-reference/units-of-measure",
      "title": "Единицы измерения",
      "trail": "Типы и вывод типов",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/units-of-measure"
    },
    {
      "id": "/dotnet/fsharp/language-reference/byrefs",
      "title": "Byref",
      "trail": "Типы и вывод типов",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/byrefs"
    },
    {
      "id": "/dotnet/fsharp/language-reference/tuples",
      "title": "Кортежи",
      "trail": "Коллекции",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/tuples"
    },
    {
      "id": "/dotnet/fsharp/language-reference/fsharp-collection-types",
      "title": "Обзор коллекций",
      "trail": "Коллекции",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/fsharp-collection-types"
    },
    {
      "id": "/dotnet/fsharp/language-reference/lists",
      "title": "Списки",
      "trail": "Коллекции",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/lists"
    },
    {
      "id": "/dotnet/fsharp/language-reference/options",
      "title": "Option",
      "trail": "Коллекции",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/options"
    },
    {
      "id": "/dotnet/fsharp/language-reference/arrays",
      "title": "Массивы",
      "trail": "Коллекции",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/arrays"
    },
    {
      "id": "/dotnet/fsharp/language-reference/sequences",
      "title": "Последовательности (seq)",
      "trail": "Коллекции",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/sequences"
    },
    {
      "id": "/dotnet/fsharp/language-reference/sequences",
      "title": "Выражения последовательностей",
      "trail": "Коллекции",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/sequences"
    },
    {
      "id": "/dotnet/fsharp/language-reference/reference-cells",
      "title": "Ссылочные ячейки",
      "trail": "Коллекции",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/reference-cells"
    },
    {
      "id": "/dotnet/fsharp/language-reference/records",
      "title": "Записи",
      "trail": "Записи и DU",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/records"
    },
    {
      "id": "/dotnet/fsharp/language-reference/anonymous-records",
      "title": "Анонимные записи",
      "trail": "Записи и DU",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/anonymous-records"
    },
    {
      "id": "/dotnet/fsharp/language-reference/discriminated-unions",
      "title": "Размеченные объединения",
      "trail": "Записи и DU",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/discriminated-unions"
    },
    {
      "id": "/dotnet/fsharp/language-reference/structs",
      "title": "Структуры",
      "trail": "Записи и DU",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/structs"
    },
    {
      "id": "/dotnet/fsharp/language-reference/enumerations",
      "title": "Перечисления",
      "trail": "Записи и DU",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/enumerations"
    },
    {
      "id": "/dotnet/fsharp/language-reference/classes",
      "title": "Классы",
      "trail": "ООП в F#",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/classes"
    },
    {
      "id": "/dotnet/fsharp/language-reference/interfaces",
      "title": "Интерфейсы",
      "trail": "ООП в F#",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/interfaces"
    },
    {
      "id": "/dotnet/fsharp/language-reference/abstract-classes",
      "title": "Абстрактные классы",
      "trail": "ООП в F#",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/abstract-classes"
    },
    {
      "id": "/dotnet/fsharp/language-reference/type-extensions",
      "title": "Расширения типов",
      "trail": "ООП в F#",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/type-extensions"
    },
    {
      "id": "/dotnet/fsharp/language-reference/delegates",
      "title": "Делегаты",
      "trail": "ООП в F#",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/delegates"
    },
    {
      "id": "/dotnet/fsharp/language-reference/inheritance",
      "title": "Наследование",
      "trail": "ООП в F#",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/inheritance"
    },
    {
      "id": "/dotnet/fsharp/language-reference/members/",
      "title": "Члены типов",
      "trail": "ООП в F#",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/members/"
    },
    {
      "id": "/dotnet/fsharp/language-reference/parameters-and-arguments",
      "title": "Параметры и аргументы",
      "trail": "ООП в F#",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/parameters-and-arguments"
    },
    {
      "id": "/dotnet/fsharp/language-reference/operator-overloading",
      "title": "Перегрузка операторов",
      "trail": "ООП в F#",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/operator-overloading"
    },
    {
      "id": "/dotnet/fsharp/language-reference/object-expressions",
      "title": "Выражения объектов",
      "trail": "ООП в F#",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/object-expressions"
    },
    {
      "id": "/dotnet/fsharp/language-reference/async-expressions",
      "title": "async { }",
      "trail": "Async, task, lazy",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/async-expressions"
    },
    {
      "id": "/dotnet/fsharp/language-reference/task-expressions",
      "title": "task { }",
      "trail": "Async, task, lazy",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/task-expressions"
    },
    {
      "id": "/dotnet/fsharp/language-reference/lazy-expressions",
      "title": "lazy",
      "trail": "Async, task, lazy",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/lazy-expressions"
    },
    {
      "id": "/dotnet/fsharp/language-reference/computation-expressions",
      "title": "Computation expressions",
      "trail": "Вычислительные выражения",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/computation-expressions"
    },
    {
      "id": "/dotnet/fsharp/language-reference/query-expressions",
      "title": "Query (LINQ)",
      "trail": "Вычислительные выражения",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/query-expressions"
    },
    {
      "id": "/dotnet/fsharp/language-reference/attributes",
      "title": "Атрибуты",
      "trail": "Метапрограммирование",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/attributes"
    },
    {
      "id": "/dotnet/fsharp/language-reference/nameof",
      "title": "nameof",
      "trail": "Метапрограммирование",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/nameof"
    },
    {
      "id": "/dotnet/fsharp/language-reference/caller-information",
      "title": "Caller Info",
      "trail": "Метапрограммирование",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/caller-information"
    },
    {
      "id": "/dotnet/fsharp/language-reference/source-line-file-path-identifiers",
      "title": "__LINE__ / __SOURCE_FILE__",
      "trail": "Метапрограммирование",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/source-line-file-path-identifiers"
    },
    {
      "id": "/dotnet/fsharp/language-reference/code-quotations",
      "title": "Кавычки кода",
      "trail": "Метапрограммирование",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/code-quotations"
    },
    {
      "id": "/dotnet/fsharp/language-reference/plaintext-formatting",
      "title": "sprintf и форматирование",
      "trail": "Метапрограммирование",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/plaintext-formatting"
    },
    {
      "id": "/dotnet/fsharp/tutorials/type-providers/",
      "title": "Обзор type providers",
      "trail": "Поставщики типов",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/tutorials/type-providers/"
    },
    {
      "id": "/dotnet/fsharp/tutorials/type-providers/creating-a-type-provider",
      "title": "Создание type provider",
      "trail": "Поставщики типов",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/tutorials/type-providers/creating-a-type-provider"
    },
    {
      "id": "/dotnet/fsharp/language-reference/keyword-reference",
      "title": "Ключевые слова",
      "trail": "Справочные таблицы",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/keyword-reference"
    },
    {
      "id": "/dotnet/fsharp/language-reference/symbol-and-operator-reference/",
      "title": "Символы и операторы",
      "trail": "Справочные таблицы",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/symbol-and-operator-reference/"
    },
    {
      "id": "/dotnet/fsharp/language-reference/compiler-options",
      "title": "Параметры компилятора",
      "trail": "Справочные таблицы",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/compiler-options"
    },
    {
      "id": "/dotnet/fsharp/language-reference/compiler-directives",
      "title": "Директивы компилятора",
      "trail": "Справочные таблицы",
      "url": "https://learn.microsoft.com/ru-ru/dotnet/fsharp/language-reference/compiler-directives"
    },
    {
      "id": "https://fsharp.github.io/fsharp-core-docs/",
      "title": "FSharp.Core API",
      "trail": "Библиотека",
      "url": "https://fsharp.github.io/fsharp-core-docs/"
    }
  ]
};
