/** Каталог франшиз раздела "Игроведение" — данные для хаба и GameFranchisePlay */

const BASE = '/encyclopedia/9-spinoff/9-03-igrovaya-industriya/game-studies';

export const GENRES = [
  {id: 'all', label: 'Все'},
  {id: 'rpg', label: 'RPG'},
  {id: 'fps', label: 'Шутеры'},
  {id: 'action', label: 'Экшен'},
  {id: 'strategy', label: 'Стратегии'},
  {id: 'fighting', label: 'Файтинги'},
  {id: 'sim', label: 'Симуляторы'},
];

export const FRANCHISES = [
  {
    id: 'diablo',
    title: 'Diablo',
    genre: 'rpg',
    icon: '🔥',
    studio: 'Blizzard',
    yearStart: 1996,
    doc: `${BASE}/1`,
    color: '#8b0000',
    tagline: 'Hack and slash, лут и подземелья Санктуария',
    specialMode: 'loot',
    releases: [
      {year: 1996, name: 'Diablo', type: 'main', platforms: 'PC', note: 'Тристрам, 3 класса, процедурные уровни'},
      {year: 1997, name: 'Hellfire', type: 'expansion', platforms: 'PC', note: 'Стороннее дополнение, класс Монах'},
      {year: 2000, name: 'Diablo II', type: 'main', platforms: 'PC, Mac', note: '5 классов, руны, сложности'},
      {year: 2001, name: 'Lord of Destruction', type: 'expansion', platforms: 'PC', note: 'Друид, Ассасин, акт Варваров'},
      {year: 2012, name: 'Diablo III', type: 'main', platforms: 'PC, консоли', note: 'Полоса действий, режим приключений'},
      {year: 2014, name: 'Reaper of Souls', type: 'expansion', platforms: 'PC, консоли', note: 'Крестоносец, Лут 2.0'},
      {year: 2021, name: 'Diablo II: Resurrected', type: 'spinoff', platforms: 'PC, консоли', note: 'Ремастер D2 + LoD'},
      {year: 2023, name: 'Diablo IV', type: 'main', platforms: 'PC, консоли', note: 'Открытый мир, сезоны, крафт'},
    ],
    mechanics: [
      {id: 'loot', label: 'Лут-цикл', desc: 'Убийство → опыт → предметы с аффиксами → билд персонажа.'},
      {id: 'proc', label: 'Процедурные уровни', desc: 'С D1 — новая геометрия подземелий при каждом прохождении.'},
      {id: 'runes', label: 'Руны и слова', desc: 'С D2 — комбинации рун для мощных наборов свойств.'},
      {id: 'season', label: 'Сезоны', desc: 'В D4 — периодические правила и эндгейм-мета.'},
    ],
    lore: [
      {id: 'sanctuary', label: 'Санктуарий', desc: 'Мир, созданный ангелами и демонами — поле битвы Порядка и Хаоса.'},
      {id: 'tristram', label: 'Тристрам', desc: 'Город над Адом; отсюда начинается сага первой части.'},
      {id: 'prime', label: 'Прайм-злы', desc: 'Диабло, Мефисто, Баал — верхушка демонического иерарха.'},
    ],
    lootTiers: [
      {id: 'common', label: 'Обычный', color: '#9ca3af', desc: 'Базовые статы без магических свойств.'},
      {id: 'magic', label: 'Магический', color: '#3b82f6', desc: '1–2 аффикса; первый скачок силы билда.'},
      {id: 'rare', label: 'Редкий', color: '#eab308', desc: 'До 6 аффиксов в D2; ядро фарма эндгейма.'},
      {id: 'set', label: 'Сетовый', color: '#22c55e', desc: 'Бонусы за комплект — целенаправленные билды.'},
      {id: 'unique', label: 'Уникальный', color: '#f97316', desc: 'Фиксированные легендарные свойства, меняют стиль игры.'},
      {id: 'legendary', label: 'Легендарный (D4)', color: '#a855f7', desc: 'Аспекты и синергии под сезонную мету.'},
    ],
  },
  {
    id: 'elder-scrolls',
    title: 'The Elder Scrolls',
    genre: 'rpg',
    icon: '🐉',
    studio: 'Bethesda Game Studios',
    yearStart: 1994,
    doc: `${BASE}/111`,
    color: '#b8860b',
    tagline: 'Открытый мир Тамриэля и абсолютная свобода игрока',
    specialMode: 'provinces',
    releases: [
      {year: 1994, name: 'Arena', type: 'main', platforms: 'MS-DOS, PC', note: 'Вся провинция как мир'},
      {year: 1996, name: 'Daggerfall', type: 'main', platforms: 'MS-DOS, PC', note: 'Масштаб и гильдии'},
      {year: 2002, name: 'Morrowind', type: 'main', platforms: 'PC, Xbox', note: 'Вварденфелл, кастомные атрибуты'},
      {year: 2006, name: 'Oblivion', type: 'main', platforms: 'PC, Xbox 360, PS3', note: 'Киродил, Radiant AI'},
      {year: 2011, name: 'Skyrim', type: 'main', platforms: 'PC, консоли', note: 'Драконы, кузня, моды'},
      {year: 2014, name: 'TES Online', type: 'spinoff', platforms: 'PC, консоли', note: 'ММО по всему Тамриэлю'},
      {year: null, name: 'TES VI', type: 'main', platforms: 'TBA', note: 'В разработке'},
    ],
    mechanics: [
      {id: 'open', label: 'Открытый мир', desc: 'Исследование без жёсткой линейности квестов.'},
      {id: 'skills', label: 'Навыки через действие', desc: 'Прокачка от использования, не от распределения очков (в классике).'},
      {id: 'mods', label: 'Моддинг', desc: 'Особенно Skyrim — тысячи TC и правок движка.'},
      {id: 'lore', label: 'Глубокий лор', desc: 'Книги, даэдра, фракции — мир читается как энциклопедия.'},
    ],
    lore: [
      {id: 'tamriel', label: 'Тамриэль', desc: 'Континент девяти провинций и множества культур.'},
      {id: 'daedra', label: 'Даэдра', desc: 'Принцы из Обливиона — квесты и артефакты серии.'},
      {id: 'dragon', label: 'Драконы', desc: 'С Skyrim — возвращение и крик Thu\'um.'},
    ],
    provinces: [
      {era: '1994–1998', place: 'Весь Тамриэль', game: 'Arena / Daggerfall', tone: 'Масштаб > детализация'},
      {era: '2002', place: 'Вварденфелл', game: 'Morrowind', tone: 'Уникальная культура данмер'},
      {era: '2006', place: 'Киродил', game: 'Oblivion', tone: 'Классическое фэнтези'},
      {era: '2011', place: 'Скайрим', game: 'Skyrim', tone: 'Скандинавский сеттинг, драконы'},
      {era: '2014+', place: 'Весь континент', game: 'ESO', tone: 'ММО-хронология Second Era'},
    ],
  },
  {
    id: 'doom',
    title: 'DOOM',
    genre: 'fps',
    icon: '💀',
    studio: 'id Software',
    yearStart: 1993,
    doc: `${BASE}/14`,
    color: '#dc2626',
    tagline: 'Родоначальник FPS и культ агрессивного темпа',
    specialMode: 'arsenal',
    releases: [
      {year: 1993, name: 'DOOM', type: 'main', platforms: 'PC', note: 'Shareware, Deathmatch, 2.5D'},
      {year: 1994, name: 'DOOM II', type: 'main', platforms: 'PC', note: 'Земля, Икона Греха'},
      {year: 2004, name: 'DOOM 3', type: 'main', platforms: 'PC, консоли', note: 'Хоррор, id Tech 4'},
      {year: 2016, name: 'DOOM', type: 'main', platforms: 'PC, консоли', note: 'Glory kills, арена'},
      {year: 2020, name: 'DOOM Eternal', type: 'main', platforms: 'PC, консоли', note: 'Ресурсный цикл боя'},
      {year: 2025, name: 'The Dark Ages', type: 'spinoff', platforms: 'PC, консоли', note: 'Приквел, ближний бой'},
    ],
    mechanics: [
      {id: 'pace', label: 'Темп', desc: 'Постоянное движение — стоять значит умирать (особенно с 2016).'},
      {id: 'glory', label: 'Glory kill', desc: 'Ближний добив для здоровья и патронов.'},
      {id: 'chainsaw', label: 'Бензопила', desc: 'В Eternal — топливо для огнемёта и ресурсов.'},
      {id: 'dm', label: 'Deathmatch', desc: 'С 1993 задал стандарт сетевого PvP-шутера.'},
    ],
    lore: [
      {id: 'marine', label: 'Думгай', desc: 'От морпеха к Палачу Рока — бессмертный страж.'},
      {id: 'uac', label: 'ОАК / UAC', desc: 'Корпорация, добывающая аргент-плазму из Ада.'},
      {id: 'hell', label: 'Ад', desc: 'Измерение демонов; порталы на Марс и Землю.'},
    ],
    weaponEras: [
      {era: '1993', label: 'Классика', weapons: ['Пистолет', 'Дробовик', 'Плазма', 'BFG 9000', 'Бензопила']},
      {era: '2016', label: 'Soft reboot', weapons: ['Супердробовик', 'Гаусс-пушка', 'Установщик модов']},
      {era: '2020', label: 'Eternal', weapons: ['Дробовик с крюком', 'Огнемёт', 'Супер-пушка', 'Цепная пила']},
    ],
  },
  {
    id: 'starcraft',
    title: 'StarCraft',
    genre: 'strategy',
    icon: '⭐',
    studio: 'Blizzard',
    yearStart: 1998,
    doc: `${BASE}/11`,
    color: '#2563eb',
    tagline: 'Космическая RTS и киберспорт Кореи',
    specialMode: 'races',
    releases: [
      {year: 1998, name: 'StarCraft', type: 'main', platforms: 'PC, Mac', note: 'Три расы, кампании, Battle.net'},
      {year: 1998, name: 'Brood War', type: 'expansion', platforms: 'PC', note: 'Новые юниты, сюжет протоссов и зергов'},
      {year: 2010, name: 'StarCraft II: Wings of Liberty', type: 'main', platforms: 'PC, Mac', note: 'Терраны, движок Trilogy'},
      {year: 2013, name: 'Heart of the Swarm', type: 'expansion', platforms: 'PC', note: 'Кампания зергов, Керриган'},
      {year: 2015, name: 'Legacy of the Void', type: 'expansion', platforms: 'PC', note: 'Протоссы, Артанис, финал сюжета'},
      {year: 2016, name: 'Nova Covert Ops', type: 'spinoff', platforms: 'PC', note: 'Миссии от третьего лица'},
    ],
    mechanics: [
      {id: 'asym', label: 'Асимметрия', desc: 'Три расы с разной экономикой и армией.'},
      {id: 'apm', label: 'APM', desc: 'Микроконтроль юнитов определяет исход на высоком уровне.'},
      {id: 'fog', label: 'Туман войны', desc: 'Разведка и информация — половина победы.'},
    ],
    lore: [
      {id: 'koprulu', label: 'Сектор Копрулу', desc: 'Человечество, протоссы и зерги в одной звёздной зоне.'},
      {id: 'overmind', label: 'Сверхразум', desc: 'Зерги как рой под коллективным сознанием.'},
      {id: 'xelnga', label: 'Ксел\'нага', desc: 'Древняя раса, связавшая происхождение трёх сторон.'},
    ],
    races: [
      {id: 'terran', label: 'Терраны', desc: 'Гибкая оборона, механика, тактика "стеной".', traits: ['бункеры', 'медики', 'танки']},
      {id: 'protoss', label: 'Протоссы', desc: 'Дорогие, но мощные юниты; псионика и щиты.', traits: ['драгоны', 'тёмные тамплиеры']},
      {id: 'zerg', label: 'Зерги', desc: 'Массовый спам, захват экономики, мутации.', traits: ['гидралиски', 'ультралиски', 'нидусы']},
    ],
  },
  {
    id: 'warcraft',
    title: 'Warcraft',
    genre: 'strategy',
    icon: '⚔️',
    studio: 'Blizzard',
    yearStart: 1994,
    doc: `${BASE}/12`,
    color: '#1d4ed8',
    tagline: 'От RTS к Azeroth и World of Warcraft',
    releases: [
      {year: 1994, name: 'Warcraft: Orcs & Humans', type: 'main', platforms: 'PC', note: 'Дуэль RTS'},
      {year: 1995, name: 'Warcraft II', type: 'main', platforms: 'PC', note: 'Морские юниты, мультиплеер Battle.net'},
      {year: 2002, name: 'Warcraft III', type: 'main', platforms: 'PC', note: 'Герои, крипы, DOTA-мод'},
      {year: 2004, name: 'World of Warcraft', type: 'spinoff', platforms: 'PC', note: 'ММОРПГ №1 эпохи'},
      {year: 2020, name: 'Warcraft III: Reforged', type: 'spinoff', platforms: 'PC', note: 'Ремастер классики'},
    ],
    mechanics: [
      {id: 'lore', label: 'Лор Азерота', desc: 'Непрерывная сага орков и людей.'},
      {id: 'mmo', label: 'MMO-наследие', desc: 'WoW задал стандарты рейдов и гильдий.'},
      {id: 'heroes', label: 'Герои WC3', desc: 'Уровни, предметы, уникальные способности на карте.'},
    ],
    lore: [
      {id: 'azeroth', label: 'Азерот', desc: 'Мир, где сходятся Альянс и Орда.'},
      {id: 'lich', label: 'Король-лич', desc: 'Поворот сюжета от RTS к эпохе нежити.'},
    ],
  },
  {
    id: 'mario',
    title: 'Super Mario',
    genre: 'action',
    icon: '🍄',
    studio: 'Nintendo',
    yearStart: 1985,
    doc: `${BASE}/112`,
    color: '#ef4444',
    tagline: 'Платформер, задавший язык жанра',
    releases: [
      {year: 1985, name: 'Super Mario Bros.', type: 'main', platforms: 'NES', note: 'Side-scrolling эталон'},
      {year: 1996, name: 'Super Mario 64', type: 'main', platforms: 'N64', note: '3D-платформер, хват за N64'},
      {year: 2007, name: 'Super Mario Galaxy', type: 'main', platforms: 'Wii', note: 'Гравитация и орбиты'},
      {year: 2017, name: 'Super Mario Odyssey', type: 'main', platforms: 'Switch', note: 'Cappy, открытые уровни-королевства'},
    ],
    mechanics: [
      {id: 'jump', label: 'Прыжок', desc: 'Точность и rhythm платформинга.'},
      {id: 'level', label: 'Дизайн уровней', desc: 'Обучение через геометрию, без текста.'},
    ],
    lore: [
      {id: 'mushroom', label: 'Грибное королевство', desc: 'Доминион принцессы Пич и Боузера.'},
      {id: 'mario', label: 'Марио', desc: 'Плоттер, ставший маскотом всей индустрии.'},
    ],
  },
  {
    id: 'gta',
    title: 'Grand Theft Auto',
    genre: 'action',
    icon: '🚗',
    studio: 'Rockstar',
    yearStart: 1997,
    doc: `${BASE}/126`,
    color: '#16a34a',
    tagline: 'Открытый мир и сатира на Америку',
    releases: [
      {year: 1997, name: 'Grand Theft Auto', type: 'main', platforms: 'PC, PS1', note: '2D, вид сверху'},
      {year: 2001, name: 'GTA III', type: 'main', platforms: 'PS2, PC', note: 'Переход в 3D'},
      {year: 2002, name: 'Vice City', type: 'main', platforms: 'PS2, PC', note: 'Атмосфера 80-х'},
      {year: 2004, name: 'San Andreas', type: 'main', platforms: 'PS2, PC', note: 'Три города, RPG-элементы'},
      {year: 2008, name: 'GTA IV', type: 'main', platforms: 'PS3, Xbox 360, PC', note: 'Реализм, физика'},
      {year: 2013, name: 'GTA V', type: 'main', platforms: 'PC, консоли', note: 'Три протагониста, GTA Online'},
      {year: 2026, name: 'GTA VI', type: 'main', platforms: 'PS5, Xbox', note: 'В разработке'},
    ],
    mechanics: [
      {id: 'sandbox', label: 'Песочница', desc: 'Свобода в городе вне сюжетных миссий.'},
      {id: 'satire', label: 'Сатира', desc: 'Пародия на американскую культуру и СМИ.'},
      {id: 'radio', label: 'Радиостанции', desc: 'Лицензированная музыка задаёт эпоху.'},
    ],
    lore: [
      {id: 'rockstar', label: 'Rockstar North', desc: 'DMA Design → культовая студия открытых миров.'},
      {id: 'online', label: 'GTA Online', desc: 'Пострелизная экономика и обновления годами.'},
    ],
  },
  {
    id: 'cod',
    title: 'Call of Duty',
    genre: 'fps',
    icon: '🎯',
    studio: 'Activision / разные студии',
    yearStart: 2003,
    doc: `${BASE}/123`,
    color: '#64748b',
    tagline: 'Ежегодный блокбастер военного шутера',
    releases: [
      {year: 2003, name: 'Call of Duty', type: 'main', platforms: 'PC', note: 'Вторая мировая, Infinity Ward'},
      {year: 2007, name: 'Modern Warfare', type: 'main', platforms: 'PC, консоли', note: 'Современная война, мультиплеер'},
      {year: 2019, name: 'Modern Warfare (reboot)', type: 'main', platforms: 'PC, консоли', note: 'Gunfight, Warzone'},
      {year: 2022, name: 'Modern Warfare II', type: 'main', platforms: 'PC, консоли', note: 'DMZ, продолжение вселенной'},
    ],
    mechanics: [
      {id: 'campaign', label: 'Кампания', desc: 'Кинематографичные миссии + мультиплеер.'},
      {id: 'annual', label: 'Ежегодный цикл', desc: 'Разные студии — общий бренд Activision.'},
    ],
    lore: [
      {id: 'mw', label: 'Modern Warfare', desc: 'Капитан Прайс и спецоперации — икона жанра.'},
      {id: 'warzone', label: 'Warzone', desc: 'Free-to-play battle royale в экосистеме COD.'},
    ],
  },
  {
    id: 'halo',
    title: 'Halo',
    genre: 'fps',
    icon: '🔵',
    studio: 'Xbox Game Studios',
    yearStart: 2001,
    doc: `${BASE}/125`,
    color: '#0ea5e9',
    tagline: 'Мастер Чиф и консольный FPS',
    releases: [
      {year: 2001, name: 'Halo: Combat Evolved', type: 'main', platforms: 'Xbox, PC', note: 'Кольцо, Ковенант'},
      {year: 2004, name: 'Halo 2', type: 'main', platforms: 'Xbox, PC', note: 'Xbox Live, двойной сюжет'},
      {year: 2007, name: 'Halo 3', type: 'main', platforms: 'Xbox 360', note: 'Финал трилогии'},
      {year: 2012, name: 'Halo 4', type: 'main', platforms: 'Xbox 360', note: 'Новая сага 343 Industries'},
      {year: 2021, name: 'Halo Infinite', type: 'main', platforms: 'Xbox, PC', note: 'Открытый сегмент Zeta Halo'},
    ],
    mechanics: [
      {id: 'shield', label: 'Щит + здоровье', desc: 'Двухслойная модель урона в шутере.'},
      {id: 'vehicles', label: 'Техника', desc: 'Варпхог и кобальт — баланс пехоты и машин.'},
    ],
    lore: [
      {id: 'chief', label: 'Мастер Чиф', desc: 'Спартанец John-117 — лицо Xbox.'},
      {id: 'ring', label: 'Кольцо Хало', desc: 'Мегаструктура Forerunner, угроза галактике.'},
    ],
  },
  {
    id: 'witcher',
    title: 'The Witcher',
    genre: 'rpg',
    icon: '🐺',
    studio: 'CD Projekt Red',
    yearStart: 2007,
    doc: `${BASE}/16`,
    color: '#7c2d12',
    tagline: 'Славянское фэнтези и моральные выборы',
    releases: [
      {year: 2007, name: 'The Witcher', type: 'main', platforms: 'PC', note: 'Моральные дилеммы, алхимия'},
      {year: 2011, name: 'The Witcher 2', type: 'main', platforms: 'PC, Xbox 360', note: 'Ветвящийся сюжет'},
      {year: 2015, name: 'The Witcher 3', type: 'main', platforms: 'PC, консоли', note: 'Открытый мир, Hearts of Stone, Blood and Wine'},
    ],
    mechanics: [
      {id: 'choice', label: 'Выборы', desc: 'Последствия квестов влияют на мир.'},
      {id: 'alchemy', label: 'Алхимия', desc: 'Зелья и масла перед боем с монстрами.'},
    ],
    lore: [
      {id: 'geralt', label: 'Геральт', desc: 'Ведьмак из Ривии — нейтралитет и контракты.'},
      {id: 'continent', label: 'Континент', desc: 'Политика королевств на фоне Второй войны.'},
    ],
  },
  {
    id: 'resident-evil',
    title: 'Resident Evil',
    genre: 'action',
    icon: '🧟',
    studio: 'Capcom',
    yearStart: 1996,
    doc: `${BASE}/115`,
    color: '#991b1b',
    tagline: 'Survival horror и биологическое оружие',
    releases: [
      {year: 1996, name: 'Resident Evil', type: 'main', platforms: 'PlayStation', note: 'Особняк, tank controls'},
      {year: 1998, name: 'Resident Evil 2', type: 'main', platforms: 'PlayStation', note: 'Раккун-Сити, два сценария'},
      {year: 2005, name: 'Resident Evil 4', type: 'main', platforms: 'GameCube', note: 'Over-the-shoulder, сельская Испания'},
      {year: 2017, name: 'Resident Evil 7', type: 'main', platforms: 'PC, консоли', note: 'От первого лица, Бейкер'},
      {year: 2023, name: 'Resident Evil 4 Remake', type: 'spinoff', platforms: 'PC, консоли', note: 'Переосмысление RE4'},
    ],
    mechanics: [
      {id: 'tension', label: 'Напряжение', desc: 'Патроны и сохранения как ресурс страха.'},
      {id: 'pivot', label: 'Смена камеры', desc: 'От фиксированных ракурсов к over-the-shoulder.'},
    ],
    lore: [
      {id: 'umbrella', label: 'Umbrella', desc: 'Корпорация, породившая биооружие.'},
      {id: 'virus', label: 'T-/G-вирус', desc: 'Мутации и зомби — ядро хоррора серии.'},
    ],
  },
  {
    id: 'street-fighter',
    title: 'Street Fighter',
    genre: 'fighting',
    icon: '👊',
    studio: 'Capcom',
    yearStart: 1987,
    doc: `${BASE}/114`,
    color: '#f59e0b',
    tagline: 'Комбо, фреймы и эволюция файтингов',
    releases: [
      {year: 1987, name: 'Street Fighter', type: 'main', platforms: 'Аркада', note: 'Рю vs Кен, 6 кнопок'},
      {year: 1991, name: 'Street Fighter II', type: 'main', platforms: 'Аркада, консоли', note: 'Глобальный феномен'},
      {year: 2016, name: 'Street Fighter V', type: 'main', platforms: 'PC, PS4', note: 'V-Trigger, Capcom Pro Tour'},
      {year: 2023, name: 'Street Fighter 6', type: 'main', platforms: 'PC, консоли', note: 'Drive Gauge, World Tour'},
    ],
    mechanics: [
      {id: 'frame', label: 'Фрейм-данные', desc: 'Точность хитбоксов и отмен.'},
      {id: 'combo', label: 'Комбо', desc: 'Ссылки и канселы — язык соревновательного файтинга.'},
    ],
    lore: [
      {id: 'world', label: 'World Warrior', desc: 'Турнир лучших бойцов планеты.'},
      {id: 'hadou', label: 'Хадокен', desc: 'Иконический снаряд Рю — символ жанра.'},
    ],
  },
  {
    id: 'mortal-kombat',
    title: 'Mortal Kombat',
    genre: 'fighting',
    icon: '🩸',
    studio: 'NetherRealm',
    yearStart: 1992,
    doc: `${BASE}/113`,
    color: '#1f2937',
    tagline: 'Жестокость и кинематографичные Fatalities',
    releases: [
      {year: 1992, name: 'Mortal Kombat', type: 'main', platforms: 'Аркада', note: 'Спор о рейтингах ESRB'},
      {year: 2011, name: 'Mortal Kombat (reboot)', type: 'main', platforms: 'PS3, Xbox 360', note: 'Сюжет альтернативной линии'},
      {year: 2019, name: 'Mortal Kombat 11', type: 'main', platforms: 'PC, консоли', note: 'Кастомизация, сюжет времени'},
    ],
    mechanics: [
      {id: 'fatality', label: 'Fatality', desc: 'Финишеры как визитная карточка серии.'},
      {id: 'brutal', label: 'Brutality / Friendship', desc: 'Вариации добиваний и пасхалок.'},
    ],
    lore: [
      {id: 'realm', label: 'Измерения', desc: 'Earthrealm, Outworld, Netherrealm.'},
      {id: 'shao', label: 'Шао Кан', desc: 'Император, объединяющий турниры Mortal Kombat.'},
    ],
  },
  {
    id: 'cyberpunk',
    title: 'Cyberpunk 2077',
    genre: 'rpg',
    icon: '🌃',
    studio: 'CD Projekt Red',
    yearStart: 2020,
    doc: `${BASE}/121`,
    color: '#facc15',
    tagline: 'Найт-Сити и RPG в сеттинге киберпанка',
    releases: [
      {year: 2020, name: 'Cyberpunk 2077', type: 'main', platforms: 'PC, консоли', note: 'Найт-Сити, V и Джонни'},
      {year: 2023, name: 'Phantom Liberty', type: 'expansion', platforms: 'PC, консоли', note: 'Шпионский сюжет, Dogtown'},
      {year: 2023, name: '2.0 / Phantom', type: 'expansion', platforms: 'PC, консоли', note: 'Переработка боёвки и полиции'},
    ],
    mechanics: [
      {id: 'build', label: 'Билды', desc: 'Киберимпланты и стили боя (стелс, хак, сила).'},
      {id: 'net', label: 'Нетраннер', desc: 'Быстрый взлом и бреши в бою.'},
    ],
    lore: [
      {id: 'night', label: 'Найт-Сити', desc: 'Мегаполис корпораций и банд.'},
      {id: 'silver', label: 'Песнь Серебряной Руки', desc: 'Настольная RPG — основа сеттинга 2077.'},
    ],
  },
  {
    id: 'overwatch',
    title: 'Overwatch',
    genre: 'fps',
    icon: '🦸',
    studio: 'Blizzard',
    yearStart: 2016,
    doc: `${BASE}/101`,
    color: '#f97316',
    tagline: 'Геройский шутер 6v6',
    releases: [
      {year: 2016, name: 'Overwatch', type: 'main', platforms: 'PC, консоли', note: 'Роли Tank/DPS/Support'},
      {year: 2022, name: 'Overwatch 2', type: 'main', platforms: 'PC, консоли', note: '5v5, PvE-риски, battle pass'},
    ],
    mechanics: [
      {id: 'roles', label: 'Роли', desc: 'Синергия ультимейтов команды.'},
      {id: 'ult', label: 'Ультимейты', desc: 'Тайминг способностей решает командные файты.'},
    ],
    lore: [
      {id: 'omnic', label: 'Кризис омников', desc: 'Роботы против человечества — предыстория мира.'},
      {id: 'watch', label: 'Overwatch', desc: 'Расформированная группа героев.'},
    ],
  },
  {
    id: 'final-fantasy',
    title: 'Final Fantasy',
    genre: 'rpg',
    icon: '💎',
    studio: 'Square Enix',
    yearStart: 1987,
    doc: `${BASE}/124`,
    color: '#6366f1',
    tagline: 'JRPG с отдельными историями в каждой части',
    releases: [
      {year: 1987, name: 'Final Fantasy', type: 'main', platforms: 'NES', note: 'Первая часть, кристаллы'},
      {year: 1997, name: 'Final Fantasy VII', type: 'main', platforms: 'PlayStation', note: 'Культовая 3D-эпоха'},
      {year: 2020, name: 'FF VII Remake', type: 'spinoff', platforms: 'PS4, PC', note: 'Переосмысление Мидгара'},
      {year: 2023, name: 'FF XVI', type: 'main', platforms: 'PS5, PC', note: 'Экшен-RPG, Валистея'},
    ],
    mechanics: [
      {id: 'turn', label: 'Пошаговый бой', desc: 'Классическая модель ATB и партий.'},
      {id: 'job', label: 'Классы / Job', desc: 'Смена ролей в бою в разных частях.'},
    ],
    lore: [
      {id: 'crystal', label: 'Кристаллы', desc: 'Мифологический каркас ранних частей.'},
      {id: 'chocobo', label: 'Чокобо', desc: 'Маскот серии и транспорт.'},
    ],
  },
  {
    id: 'sims',
    title: 'The Sims',
    genre: 'sim',
    icon: '🏠',
    studio: 'Maxis / EA',
    yearStart: 2000,
    doc: `${BASE}/17`,
    color: '#22c55e',
    tagline: 'Жизненный симулятор без явной цели победы',
    releases: [
      {year: 2000, name: 'The Sims', type: 'main', platforms: 'PC', note: 'Потребности, карьера, дом'},
      {year: 2004, name: 'The Sims 2', type: 'main', platforms: 'PC', note: 'Возраст, генетика, аспирации'},
      {year: 2014, name: 'The Sims 4', type: 'main', platforms: 'PC, консоли', note: 'Эмоции, CAS, DLC-экосистема'},
    ],
    mechanics: [
      {id: 'needs', label: 'Потребности', desc: 'Голод, гигиена, социализация — цикл дня.'},
      {id: 'sandbox', label: 'Песочница жизни', desc: 'Нет условия "победы" — цель задаёт игрок.'},
    ],
    lore: [
      {id: 'will', label: 'Wright', desc: 'Уилл Райт — автор SimCity и The Sims.'},
      {id: 'dlc', label: 'DLC-экспансии', desc: 'Пакеты профессий, миров и стилей.'},
    ],
  },
  {
    id: 'monster-hunter',
    title: 'Monster Hunter',
    genre: 'action',
    icon: '🗡️',
    studio: 'Capcom',
    yearStart: 2004,
    doc: `${BASE}/13`,
    color: '#78716c',
    tagline: 'Охота на гигантов и крафт из частей',
    releases: [
      {year: 2004, name: 'Monster Hunter', type: 'main', platforms: 'PS2', note: 'Охота в команде, крафт'},
      {year: 2018, name: 'Monster Hunter: World', type: 'main', platforms: 'PC, консоли', note: 'Глобальный хит, упрощённый вход'},
      {year: 2021, name: 'Monster Hunter Rise', type: 'main', platforms: 'Switch, PC', note: 'Вайр-баг и палико'},
      {year: 2025, name: 'Monster Hunter Wilds', type: 'main', platforms: 'PC, консоли', note: 'Открытые зоны, погода'},
    ],
    mechanics: [
      {id: 'craft', label: 'Крафт из трофеев', desc: 'Броня и оружие из материалов монстра.'},
      {id: 'prep', label: 'Подготовка', desc: 'Еда, зелья и знание слабостей цели.'},
    ],
    lore: [
      {id: 'guild', label: 'Гильдия охотников', desc: 'Контракты и ранг охотника.'},
      {id: 'ecosystem', label: 'Экосистема', desc: 'Монстры ведут себя как часть мира.'},
    ],
  },
  {
    id: 'warhammer',
    title: 'Warhammer',
    genre: 'strategy',
    icon: '⚜️',
    studio: 'Разные (Games Workshop лицензия)',
    yearStart: 1995,
    doc: `${BASE}/15`,
    color: '#4b5563',
    tagline: 'Вселенная Fantasy и 40K в десятках игр',
    releases: [
      {year: 1995, name: 'Warhammer: Shadow of the Horned Rat', type: 'spinoff', platforms: 'PC', note: 'RTS Fantasy'},
      {year: 2004, name: 'Dawn of War', type: 'spinoff', platforms: 'PC', note: 'RTS в сеттинге 40K'},
      {year: 2016, name: 'Total War: Warhammer', type: 'spinoff', platforms: 'PC', note: 'Пошаговая карта + битвы'},
      {year: 2023, name: 'Darktide', type: 'spinoff', platforms: 'PC, консоли', note: 'Co-op FPS 40K'},
    ],
    mechanics: [
      {id: 'ip', label: 'Трансмедиа', desc: 'Настолки, книги, игры — единый лор.'},
      {id: '40k', label: 'Warhammer 40,000', desc: '"В галактике нет ничего, кроме войны".'},
    ],
    lore: [
      {id: 'fantasy', label: 'Fantasy', desc: 'Старый мир — орки, эльфы, империя.'},
      {id: '40k', label: '40K', desc: 'Космические марины и Империум человечества.'},
    ],
  },
  {
    id: 'far-cry',
    title: 'Far Cry',
    genre: 'fps',
    icon: '🏝️',
    studio: 'Ubisoft',
    yearStart: 2004,
    doc: `${BASE}/116`,
    color: '#059669',
    tagline: 'Открытый мир и харизматичные злодеи',
    releases: [
      {year: 2004, name: 'Far Cry', type: 'main', platforms: 'PC', note: 'Остров, открытые километры'},
      {year: 2012, name: 'Far Cry 3', type: 'main', platforms: 'PC, консоли', note: 'Ваас, остров, outposts'},
      {year: 2014, name: 'Far Cry 4', type: 'main', platforms: 'PC, консоли', note: 'Гималаи, Пэган Мин'},
      {year: 2021, name: 'Far Cry 6', type: 'main', platforms: 'PC, консоли', note: 'Яра, революция'},
    ],
    mechanics: [
      {id: 'open', label: 'Outposts', desc: 'Захват точек и свободное исследование.'},
      {id: 'villain', label: 'Антагонист', desc: 'Харизматичные злодеи — визитная карточка FC3+.'},
    ],
    lore: [
      {id: 'island', label: 'Острова', desc: 'Изолированные локации с дикой природой.'},
      {id: 'ubisoft', label: 'Ubisoft', desc: 'Формула открытого мира и башен на карте.'},
    ],
  },
  {
    id: 'assassins-creed',
    title: "Assassin's Creed",
    genre: 'action',
    icon: '🦅',
    studio: 'Ubisoft',
    yearStart: 2007,
    doc: `${BASE}/117`,
    color: '#1e3a5f',
    tagline: 'Исторические открытые миры и стелс-убийства',
    releases: [
      {year: 2007, name: "Assassin's Creed", type: 'main', platforms: 'PC, консоли', note: 'Святилище, паркур'},
      {year: 2009, name: "Assassin's Creed II", type: 'main', platforms: 'PC, консоли', note: 'Эцио, Ренессанс'},
      {year: 2017, name: "Origins", type: 'main', platforms: 'PC, консоли', note: 'RPG-система, Древний Египет'},
      {year: 2020, name: 'Valhalla', type: 'main', platforms: 'PC, консоли', note: 'Викинги, Англия'},
    ],
    mechanics: [
      {id: 'parkour', label: 'Паркур', desc: 'Вертикальность городов и крыши.'},
      {id: 'animus', label: 'Анимус', desc: 'Воспоминания предков — рамка сюжета.'},
    ],
    lore: [
      {id: 'assassins', label: 'Ассасины vs Тамплиеры', desc: 'Свобода воли против порядка.'},
      {id: 'pieces', label: 'Кусочки Эдема', desc: 'Артефакты Предтеч — сквозная мифология.'},
    ],
  },
  {
    id: 'dragon-age',
    title: 'Dragon Age',
    genre: 'rpg',
    icon: '🐲',
    studio: 'BioWare',
    yearStart: 2009,
    doc: `${BASE}/118`,
    color: '#7f1d1d',
    tagline: 'Партия, романсы и политика Феральдена',
    releases: [
      {year: 2009, name: 'Dragon Age: Origins', type: 'main', platforms: 'PC, консоли', note: 'Тактическая пауза'},
      {year: 2011, name: 'Dragon Age II', type: 'main', platforms: 'PC, консоли', note: 'Киркволл, один герой'},
      {year: 2014, name: 'Dragon Age: Inquisition', type: 'main', platforms: 'PC, консоли', note: 'Открытый мир, Солас'},
      {year: 2024, name: 'Dragon Age: The Veilguard', type: 'main', platforms: 'PC, консоли', note: 'Новая часть с акцентом на экшен'},
    ],
    mechanics: [
      {id: 'party', label: 'Партия', desc: 'Отношения с компаньонами меняют сюжет.'},
      {id: 'choices', label: 'Мораль', desc: 'Решения влияют на политику Феральдена и мир.'},
    ],
    lore: [
      {id: 'ferelden', label: 'Феральден', desc: 'Королевство людей и Blight.'},
      {id: 'grey', label: 'Серые Стражи', desc: 'Орден против тёмных порождений.'},
    ],
  },
  {
    id: 'devil-may-cry',
    title: 'Devil May Cry',
    genre: 'action',
    icon: '😈',
    studio: 'Capcom',
    yearStart: 2001,
    doc: `${BASE}/119`,
    color: '#9333ea',
    tagline: 'Стиль, комбо и hack-and-slash эталон',
    releases: [
      {year: 2001, name: 'Devil May Cry', type: 'main', platforms: 'PlayStation 2', note: 'Ранг стиля SSS'},
      {year: 2019, name: 'Devil May Cry 5', type: 'main', platforms: 'PC, консоли', note: 'Неро, Ви, Данте'},
      {year: 2023, name: 'Peak of Combat', type: 'mobile', platforms: 'iOS, Android', note: 'Мобильная адаптация'},
    ],
    mechanics: [
      {id: 'style', label: 'Style meter', desc: 'Награда за разнообразие приёмов.'},
      {id: 'juggle', label: 'Джаггл', desc: 'Подбрасывание врагов в воздухе.'},
    ],
    lore: [
      {id: 'dante', label: 'Данте', desc: 'Охотник на демонов, агентство Devil May Cry.'},
      {id: 'sparda', label: 'Спарда', desc: 'Демон-легенда, отец героев.'},
    ],
  },
  {
    id: 'dead-space',
    title: 'Dead Space',
    genre: 'action',
    icon: '👾',
    studio: 'Motive / EA',
    yearStart: 2008,
    doc: `${BASE}/120`,
    color: '#334155',
    tagline: 'Космический хоррор и некроморфы',
    releases: [
      {year: 2008, name: 'Dead Space', type: 'main', platforms: 'PC, консоли', note: 'Ишимура, некроморфы'},
      {year: 2011, name: 'Dead Space 2', type: 'main', platforms: 'PC, консоли', note: 'Станция Спрью'},
      {year: 2013, name: 'Dead Space 3', type: 'main', platforms: 'PC, консоли', note: 'Кооп, Луна'},
      {year: 2023, name: 'Dead Space Remake', type: 'spinoff', platforms: 'PC, консоли', note: 'Ремейк первой части'},
    ],
    mechanics: [
      {id: 'limb', label: 'Дизмембермент', desc: 'Стрельба по конечностям, а не только в тело.'},
      {id: 'atm', label: 'Атмосфера', desc: 'Звук, тишина, вентиляция — хоррор без скримеров.'},
    ],
    lore: [
      {id: 'marker', label: 'Маркер', desc: 'Артефакт, сводящий людей с ума.'},
      {id: 'necro', label: 'Некроморф', desc: 'Мутанты из мёртвой плоти.'},
    ],
  },
  {
    id: 'crysis',
    title: 'Crysis',
    genre: 'fps',
    icon: '🧊',
    studio: 'Crytek',
    yearStart: 2007,
    doc: `${BASE}/122`,
    color: '#38bdf8',
    tagline: 'Нанокостюм и эталон графики эпохи',
    releases: [
      {year: 2007, name: 'Crysis', type: 'main', platforms: 'PC', note: '"Can it run Crysis?"'},
      {year: 2011, name: 'Crysis 2', type: 'main', platforms: 'PC, консоли', note: 'Нью-Йорк, вирус Ceph'},
      {year: 2013, name: 'Crysis 3', type: 'main', platforms: 'PC, консоли', note: 'Купол над NYC'},
      {year: 2021, name: 'Crysis Remastered Trilogy', type: 'spinoff', platforms: 'PC, консоли', note: 'Обновлённая трилогия'},
    ],
    mechanics: [
      {id: 'suit', label: 'Костюм', desc: 'Режимы силы, скорости, маскировки.'},
      {id: 'sandbox', label: 'Песочница боя', desc: 'Разрушаемость и тактика на открытой карте.'},
    ],
    lore: [
      {id: 'ceph', label: 'Ceph', desc: 'Инопланетная угроза в арктике и мегаполисах.'},
      {id: 'cryengine', label: 'CryEngine', desc: 'Движок, задавший планку графики PC.'},
    ],
  },
];

/** doc path suffix (e.g. "11") → franchise id */
export const DOC_FRANCHISE_MAP = {
  '1': 'diablo',
  '11': 'starcraft',
  '12': 'warcraft',
  '13': 'monster-hunter',
  '14': 'doom',
  '15': 'warhammer',
  '16': 'witcher',
  '17': 'sims',
  '101': 'overwatch',
  '111': 'elder-scrolls',
  '112': 'mario',
  '113': 'mortal-kombat',
  '114': 'street-fighter',
  '115': 'resident-evil',
  '116': 'far-cry',
  '117': 'assassins-creed',
  '118': 'dragon-age',
  '119': 'devil-may-cry',
  '120': 'dead-space',
  '121': 'cyberpunk',
  '122': 'crysis',
  '123': 'cod',
  '124': 'final-fantasy',
  '125': 'halo',
  '126': 'gta',
};

export function getFranchise(id) {
  return FRANCHISES.find((f) => f.id === id) ?? null;
}

export const RELEASE_TYPES = {
  main: {label: 'Основная', color: '#3b82f6'},
  expansion: {label: 'Дополнение', color: '#8b5cf6'},
  spinoff: {label: 'Спин-офф', color: '#f59e0b'},
  mobile: {label: 'Мобильная', color: '#10b981'},
};
