/**
 * Курируемый каталог официальной документации Kubernetes (kubernetes.io).
 * Тексты статей не копируются — только названия разделов и ссылки.
 * @see https://kubernetes.io/ru/docs/home/
 */

export const K8S_DOC_FILTERS = [
  {id: 'all', label: 'Все'},
  {id: 'overview', label: 'Обзор'},
  {id: 'setup', label: 'Настройка'},
  {id: 'api', label: 'API'},
  {id: 'workloads', label: 'Нагрузки'},
  {id: 'network', label: 'Сеть'},
  {id: 'storage', label: 'Хранилище'},
  {id: 'config', label: 'Конфигурация'},
  {id: 'security', label: 'Безопасность'},
  {id: 'admin', label: 'Администрирование'},
  {id: 'tools', label: 'Инструменты'},
  {id: 'tasks', label: 'Задачи'},
  {id: 'extend', label: 'Расширения'},
];

/** @typedef {'RU' | 'EN' | 'RU/EN'} K8sDocLang */

export const KUBERNETES_DOC_ITEMS = [
  {
    id: 'home-ru',
    section: 'overview',
    lang: 'RU',
    title: 'Документация Kubernetes (хаб)',
    summary: 'Точка входа: концепции, руководства, настройка кластера, задачи и справочник.',
    url: 'https://kubernetes.io/ru/docs/home/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/117',
  },
  {
    id: 'what-is-k8s',
    section: 'overview',
    lang: 'RU',
    title: 'Что такое Kubernetes',
    summary:
      'История (физические серверы → VM → контейнеры), зачем нужен оркестратор, возможности и чем K8s не является.',
    url: 'https://kubernetes.io/ru/docs/concepts/overview/what-is-kubernetes/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/117',
  },
  {
    id: 'components',
    section: 'overview',
    lang: 'RU',
    title: 'Компоненты Kubernetes',
    summary: 'Control plane (apiserver, etcd, scheduler, controller-manager) и узлы (kubelet, kube-proxy, CRI).',
    url: 'https://kubernetes.io/ru/docs/concepts/overview/components/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/117',
  },
  {
    id: 'concepts-hub',
    section: 'overview',
    lang: 'RU',
    title: 'Концепции (раздел)',
    summary: 'Объекты API, control plane, Pod, Deployment и абстракции высокого уровня.',
    url: 'https://kubernetes.io/ru/docs/concepts/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/211',
  },
  {
    id: 'k8s-api',
    section: 'api',
    lang: 'RU',
    title: 'API Kubernetes',
    summary: 'Версионирование (alpha/beta/stable), группы API, OpenAPI, etcd, kubectl как клиент API.',
    url: 'https://kubernetes.io/ru/docs/concepts/overview/kubernetes-api/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/211',
  },
  {
    id: 'working-with-objects',
    section: 'api',
    lang: 'RU',
    title: 'Работа с объектами Kubernetes',
    summary: 'Имена, метки, аннотации, поля spec/status, управление объектами и общие операции.',
    url: 'https://kubernetes.io/ru/docs/concepts/overview/working-with-objects/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/211',
  },
  {
    id: 'api-reference',
    section: 'api',
    lang: 'RU/EN',
    title: 'Справочник API',
    summary: 'Полный перечень ресурсов, полей и версий apiVersion/kind.',
    url: 'https://kubernetes.io/ru/docs/reference/kubernetes-api/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/211',
  },
  {
    id: 'setup-hub',
    section: 'setup',
    lang: 'RU',
    title: 'Настройка кластера',
    summary: 'Локальная среда, managed, turnkey-облако, on-prem и кастомные решения.',
    url: 'https://kubernetes.io/ru/docs/setup/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/117',
  },
  {
    id: 'learning-env',
    section: 'setup',
    lang: 'RU',
    title: 'Среда обучения (Minikube, kind)',
    summary: 'Запуск кластера на ноутбуке для экспериментов и разработки.',
    url: 'https://kubernetes.io/ru/docs/setup/learning-environment/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/1172',
  },
  {
    id: 'install-tools',
    section: 'tools',
    lang: 'RU',
    title: 'Установка инструментов',
    summary: 'kubectl, minikube, kubeadm — бинарники и пакетные менеджеры.',
    url: 'https://kubernetes.io/ru/docs/tasks/tools/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/1172',
  },
  {
    id: 'install-kubectl',
    section: 'tools',
    lang: 'RU',
    title: 'Установка kubectl',
    summary: 'Клиент командной строки для API кластера; конфиг kubeconfig.',
    url: 'https://kubernetes.io/ru/docs/tasks/tools/install-kubectl/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/1172',
  },
  {
    id: 'install-minikube',
    section: 'tools',
    lang: 'RU',
    title: 'Установка Minikube',
    summary: 'Одноузловой локальный кластер для обучения и отладки.',
    url: 'https://kubernetes.io/ru/docs/tasks/tools/install-minikube/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/1172',
  },
  {
    id: 'install-kubeadm',
    section: 'setup',
    lang: 'EN',
    title: 'Installing kubeadm',
    summary: 'Подготовка узлов, bootstrap control plane, присоединение worker-нод.',
    url: 'https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/117',
  },
  {
    id: 'certificates-manual',
    section: 'setup',
    lang: 'EN',
    title: 'Certificate management with kubeadm',
    summary: 'Генерация и ротация сертификатов control plane вручную.',
    url: 'https://kubernetes.io/docs/tasks/administer-cluster/certificates/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/117',
  },
  {
    id: 'kubectl-overview',
    section: 'tools',
    lang: 'RU',
    title: 'kubectl — обзор',
    summary: 'Синтаксис, контексты, namespaces, императивные и декларативные команды.',
    url: 'https://kubernetes.io/ru/docs/reference/kubectl/overview/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/211',
  },
  {
    id: 'kubectl-cheat',
    section: 'tools',
    lang: 'EN',
    title: 'kubectl command-line tool',
    summary: 'Полный справочник подкоманд, флагов и примеров (актуальная EN-версия).',
    url: 'https://kubernetes.io/docs/reference/kubectl/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/211',
  },
  {
    id: 'cluster-architecture',
    section: 'overview',
    lang: 'RU',
    title: 'Кластерная архитектура',
    summary: 'Узлы, control plane, контроллеры, высокая доступность и топологии.',
    url: 'https://kubernetes.io/ru/docs/concepts/architecture/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/117',
  },
  {
    id: 'nodes',
    section: 'overview',
    lang: 'RU',
    title: 'Узлы (Nodes)',
    summary: 'Роли узлов, taints/tolerations, условия Ready и взаимодействие с kubelet.',
    url: 'https://kubernetes.io/ru/docs/concepts/architecture/nodes/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/117',
  },
  {
    id: 'containers',
    section: 'workloads',
    lang: 'RU',
    title: 'Контейнеры',
    summary: 'Образы, runtime, CRI, переменные окружения и жизненный цикл контейнера в Pod.',
    url: 'https://kubernetes.io/ru/docs/concepts/containers/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/111',
  },
  {
    id: 'pods-config',
    section: 'config',
    lang: 'RU',
    title: 'Настройка Pod и контейнеров',
    summary: 'Команды, args, probes, resources, securityContext, volumeMounts.',
    url: 'https://kubernetes.io/ru/docs/concepts/workloads/pods/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/211',
  },
  {
    id: 'workloads',
    section: 'workloads',
    lang: 'RU',
    title: 'Рабочие нагрузки',
    summary: 'Pod, ReplicaSet, Deployment, StatefulSet, DaemonSet, Job, CronJob.',
    url: 'https://kubernetes.io/ru/docs/concepts/workloads/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/211',
  },
  {
    id: 'deployments',
    section: 'workloads',
    lang: 'RU',
    title: 'Deployments',
    summary: 'Декларативные обновления, Rolling Update, откат, масштабирование реплик.',
    url: 'https://kubernetes.io/ru/docs/concepts/workloads/controllers/deployment/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/1171',
  },
  {
    id: 'services-networking',
    section: 'network',
    lang: 'EN',
    title: 'Services, Load Balancing, and Networking',
    summary: 'Service (ClusterIP/NodePort/LB), Ingress, NetworkPolicy, DNS в кластере.',
    url: 'https://kubernetes.io/docs/concepts/services-networking/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/1171',
  },
  {
    id: 'service-ru',
    section: 'network',
    lang: 'RU',
    title: 'Service (сервис)',
    summary: 'Стабильный endpoint для Pod, селекторы, порты и балансировка.',
    url: 'https://kubernetes.io/ru/docs/concepts/services-networking/service/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/1171',
  },
  {
    id: 'ingress-ru',
    section: 'network',
    lang: 'RU',
    title: 'Ingress',
    summary: 'HTTP/HTTPS-маршрутизация во внутренние Service; нужен Ingress Controller.',
    url: 'https://kubernetes.io/ru/docs/concepts/services-networking/ingress/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/1171',
  },
  {
    id: 'storage',
    section: 'storage',
    lang: 'EN',
    title: 'Storage',
    summary: 'Volumes, PV, PVC, StorageClass, динамическое выделение томов.',
    url: 'https://kubernetes.io/docs/concepts/storage/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/211',
  },
  {
    id: 'pv-pvc',
    section: 'storage',
    lang: 'RU',
    title: 'Persistent Volumes и Claims',
    summary: 'Запрос хранилища для Pod, привязка PV к PVC, reclaim policy.',
    url: 'https://kubernetes.io/ru/docs/concepts/storage/persistent-volumes/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/211',
  },
  {
    id: 'configuration',
    section: 'config',
    lang: 'EN',
    title: 'Configuration',
    summary: 'ConfigMap, Secret, projected volumes, downward API.',
    url: 'https://kubernetes.io/docs/concepts/configuration/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/211',
  },
  {
    id: 'configmap',
    section: 'config',
    lang: 'RU',
    title: 'ConfigMap',
    summary: 'Несекретные параметры конфигурации как ключ-значение или файлы.',
    url: 'https://kubernetes.io/ru/docs/concepts/configuration/configmap/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/211',
  },
  {
    id: 'secrets',
    section: 'config',
    lang: 'RU',
    title: 'Secrets',
    summary: 'Opaque, TLS, registry; data/stringData, env и volume, etcd encryption, ESO/Sealed Secrets.',
    url: 'https://kubernetes.io/ru/docs/concepts/configuration/secret/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/211',
  },
  {
    id: 'security',
    section: 'security',
    lang: 'EN',
    title: 'Security',
    summary: 'Аутентификация, авторизация RBAC, admission, Pod Security, service accounts.',
    url: 'https://kubernetes.io/docs/concepts/security/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/211',
  },
  {
    id: 'rbac',
    section: 'security',
    lang: 'RU',
    title: 'RBAC — управление доступом',
    summary: 'Role, ClusterRole, RoleBinding и принцип наименьших привилегий.',
    url: 'https://kubernetes.io/ru/docs/reference/access-authn-authz/rbac/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/211',
  },
  {
    id: 'policies',
    section: 'security',
    lang: 'EN',
    title: 'Policies',
    summary: 'LimitRange, ResourceQuota, NetworkPolicy, Pod Security Admission.',
    url: 'https://kubernetes.io/docs/concepts/policy/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/211',
  },
  {
    id: 'scheduling',
    section: 'workloads',
    lang: 'RU',
    title: 'Планирование, приоритизация и вытеснение',
    summary: 'Scheduler, affinity/anti-affinity, PriorityClass, preemption, eviction.',
    url: 'https://kubernetes.io/ru/docs/concepts/scheduling-eviction/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/211',
  },
  {
    id: 'cluster-admin',
    section: 'admin',
    lang: 'RU',
    title: 'Администрирование кластера',
    summary: 'Логирование, мониторинг, addons, обновления и эксплуатация.',
    url: 'https://kubernetes.io/ru/docs/concepts/cluster-administration/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/1171',
  },
  {
    id: 'logging',
    section: 'admin',
    lang: 'RU',
    title: 'Логирование кластера',
    summary: 'Логи контейнеров, node-level logging, централизованный сбор.',
    url: 'https://kubernetes.io/ru/docs/concepts/cluster-administration/logging/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/211',
  },
  {
    id: 'extend-k8s',
    section: 'extend',
    lang: 'RU',
    title: 'Расширения Kubernetes',
    summary: 'CRD, операторы, API aggregation, webhooks и кастомные контроллеры.',
    url: 'https://kubernetes.io/ru/docs/concepts/extend-kubernetes/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/211',
  },
  {
    id: 'crd',
    section: 'extend',
    lang: 'EN',
    title: 'Custom Resources',
    summary: 'CustomResourceDefinition и расширение API без форка Kubernetes.',
    url: 'https://kubernetes.io/docs/concepts/extend-kubernetes/api-extension/custom-resources/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/211',
  },
  {
    id: 'windows',
    section: 'extend',
    lang: 'EN',
    title: 'Windows in Kubernetes',
    summary: 'Windows-узлы, ограничения runtime и смешанные кластеры Linux/Windows.',
    url: 'https://kubernetes.io/docs/concepts/windows/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/117',
  },
  {
    id: 'tasks-hub',
    section: 'tasks',
    lang: 'EN',
    title: 'Tasks',
    summary: 'Пошаговые инструкции: администрирование, приложения, отладка, безопасность.',
    url: 'https://kubernetes.io/docs/tasks/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/1172',
  },
  {
    id: 'hello-minikube',
    section: 'tasks',
    lang: 'RU',
    title: 'Привет, Minikube',
    summary: 'Первое приложение в кластере: Deployment и Service.',
    url: 'https://kubernetes.io/ru/docs/tutorials/hello-minikube/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/1172',
  },
  {
    id: 'basics-tutorial',
    section: 'tasks',
    lang: 'RU',
    title: 'Краткий обзор основ',
    summary: 'Интерактивный тур: Pod, Deployment, Service, масштабирование.',
    url: 'https://kubernetes.io/ru/docs/tutorials/kubernetes-basics/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/1172',
  },
  {
    id: 'glossary',
    section: 'overview',
    lang: 'RU/EN',
    title: 'Глоссарий Kubernetes',
    summary: 'Определения терминов: Pod, Node, Namespace, CRI и др.',
    url: 'https://kubernetes.io/ru/docs/reference/glossary/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/211',
  },
  {
    id: 'download',
    section: 'setup',
    lang: 'RU/EN',
    title: 'Скачать Kubernetes',
    summary: 'Версии бинарников, changelog и совместимость компонентов.',
    url: 'https://kubernetes.io/releases/download/',
    encyclopedia: '/encyclopedia/8-infra-security/8-06-konteynerizatsiya-i-orkestratsiya/117',
  },
];
