/**
 * Курируемый каталог Microsoft Learn (RU).
 * Метаданные и ссылки — по условиям Catalog API; тексты модулей не копируются.
 * @see https://learn.microsoft.com/en-us/training/support/catalog-api-developer-reference
 */

export const LEARN_FILTERS = [
  {id: 'all', label: 'Все'},
  {id: 'basics', label: 'Основы'},
  {id: 'system', label: 'Система'},
  {id: 'data', label: 'Данные'},
  {id: 'code', label: 'Разработка'},
  {id: 'languages', label: 'Языки'},
  {id: 'ai', label: 'ИИ'},
  {id: 'project', label: 'Проект'},
  {id: 'infra', label: 'Инфра'},
];

export const LEARN_LEVELS = [
  {id: 'all', label: 'Любой уровень'},
  {id: 'beginner', label: 'Начальный'},
  {id: 'intermediate', label: 'Средний'},
  {id: 'advanced', label: 'Расширенный'},
];

/** type: path | module | course */
export const MICROSOFT_LEARN_ITEMS = [
  {
    id: 'az-fund-cloud',
    type: 'path',
    section: 'infra',
    level: 'beginner',
    role: 'Администратор',
    product: 'Azure',
    title: 'Облачная инфраструктура: облачные концепции',
    durationMin: 56,
    url: 'https://learn.microsoft.com/ru-ru/training/paths/microsoft-azure-fundamentals-describe-cloud-concepts/',
    summary: 'IaaS/PaaS/SaaS, модели развёртывания, экономика облака. После теории в 8.01.',
    encyclopedia: '/encyclopedia/8-infra-security/8-01-oblachnye-tehnologii/12',
  },
  {
    id: 'az-fund-arch',
    type: 'path',
    section: 'infra',
    level: 'beginner',
    role: 'Администратор',
    product: 'Azure',
    title: 'Архитектура и службы Azure',
    durationMin: 168,
    url: 'https://learn.microsoft.com/ru-ru/training/paths/azure-fundamentals-describe-azure-architecture-services/',
    summary: 'Compute, storage, сеть, базовые PaaS-сервисы.',
    encyclopedia: '/encyclopedia/8-infra-security/8-01-oblachnye-tehnologii/1',
  },
  {
    id: 'az-fund-gov',
    type: 'path',
    section: 'infra',
    level: 'beginner',
    role: 'Администратор',
    product: 'Azure',
    title: 'Управление и соответствие в Azure',
    durationMin: 81,
    url: 'https://learn.microsoft.com/ru-ru/training/paths/describe-azure-management-governance/',
    summary: 'Подписки, RBAC, Policy, мониторинг на уровне облака.',
    encyclopedia: '/encyclopedia/8-infra-security/8-01-oblachnye-tehnologii/12',
  },
  {
    id: 'mod-cloud-benefits',
    type: 'module',
    section: 'infra',
    level: 'beginner',
    role: 'Администратор',
    product: 'Azure',
    title: 'Преимущества облачных служб',
    durationMin: 19,
    url: 'https://learn.microsoft.com/ru-ru/training/modules/describe-benefits-use-cloud-services/',
    summary: 'CAPEX vs OPEX, эластичность, геораспределение.',
    encyclopedia: '/encyclopedia/8-infra-security/8-01-oblachnye-tehnologii/12',
  },
  {
    id: 'mod-cloud-types',
    type: 'module',
    section: 'infra',
    level: 'beginner',
    role: 'Администратор',
    product: 'Azure',
    title: 'Типы облачных служб',
    durationMin: 13,
    url: 'https://learn.microsoft.com/ru-ru/training/modules/describe-cloud-service-types/',
    summary: 'IaaS, PaaS, SaaS на примерах Azure.',
    encyclopedia: '/encyclopedia/8-infra-security/8-01-oblachnye-tehnologii/12',
  },
  {
    id: 'csharp-part1',
    type: 'path',
    section: 'languages',
    level: 'beginner',
    role: 'Разработчик',
    product: '.NET',
    title: 'Первый код на C# (часть 1)',
    durationMin: 277,
    url: 'https://learn.microsoft.com/ru-ru/training/paths/get-started-c-sharp-part-1/',
    summary: 'Синтаксис, типы, операторы, первая консольная программа.',
    encyclopedia: '/encyclopedia/5-languages/5-05-csharp/454',
  },
  {
    id: 'csharp-part2',
    type: 'path',
    section: 'languages',
    level: 'beginner',
    role: 'Разработчик',
    product: '.NET',
    title: 'Консольные приложения C# (часть 2)',
    durationMin: 400,
    url: 'https://learn.microsoft.com/ru-ru/training/paths/get-started-c-sharp-part-2/',
    summary: 'Методы, массивы, отладка, мини-проекты.',
    encyclopedia: '/encyclopedia/5-languages/5-05-csharp/454',
  },
  {
    id: 'mod-csharp-first',
    type: 'module',
    section: 'languages',
    level: 'beginner',
    role: 'Разработчик',
    product: '.NET',
    title: 'Написание первого кода C#',
    durationMin: 27,
    url: 'https://learn.microsoft.com/ru-ru/training/modules/csharp-write-first/',
    summary: 'Hello World и запуск в dotnet или VS Code.',
    encyclopedia: '/encyclopedia/5-languages/5-05-csharp/1',
  },
  {
    id: 'mod-vscode',
    type: 'module',
    section: 'code',
    level: 'beginner',
    role: 'Разработчик',
    product: 'Visual Studio Code',
    title: 'Установка и настройка VS Code',
    durationMin: 42,
    url: 'https://learn.microsoft.com/ru-ru/training/modules/install-configure-visual-studio-code/',
    summary: 'Расширения C#, терминал, отладка.',
    encyclopedia: '/encyclopedia/1-basics/1-13-soft-prodvinutogo-polzovatelya/3',
  },
  {
    id: 'ai-fundamentals',
    type: 'module',
    section: 'ai',
    level: 'beginner',
    role: 'Инженер ИИ',
    product: 'Azure',
    title: 'Концепции ИИ',
    durationMin: 40,
    url: 'https://learn.microsoft.com/ru-ru/training/modules/get-started-ai-fundamentals/',
    summary: 'ML, ответственный ИИ, сценарии в бизнесе.',
    encyclopedia: '/encyclopedia/6-ai/6-01-vvedenie-v-ii/12',
  },
  {
    id: 'gen-ai-fund',
    type: 'module',
    section: 'ai',
    level: 'beginner',
    role: 'Инженер ИИ',
    product: 'Azure',
    title: 'Генеративный ИИ и агенты — введение',
    durationMin: 37,
    url: 'https://learn.microsoft.com/ru-ru/training/modules/fundamentals-generative-ai/',
    summary: 'LLM, промпты, RAG, агенты на высоком уровне.',
    encyclopedia: '/encyclopedia/6-ai/6-01-vvedenie-v-ii/12',
  },
  {
    id: 'ml-fund',
    type: 'module',
    section: 'ai',
    level: 'beginner',
    role: 'Инженер ИИ',
    product: 'Azure',
    title: 'Концепции машинного обучения',
    durationMin: 93,
    url: 'https://learn.microsoft.com/ru-ru/training/modules/fundamentals-machine-learning/',
    summary: 'Обучение с учителем и без, метрики, Azure ML обзорно.',
    encyclopedia: '/encyclopedia/6-ai/6-02-mashinnoe-obuchenie/1',
  },
  {
    id: 'ai-agents-azure',
    type: 'module',
    section: 'ai',
    level: 'beginner',
    role: 'Инженер ИИ',
    product: 'Azure',
    title: 'Разработка агента ИИ в Azure',
    durationMin: 49,
    url: 'https://learn.microsoft.com/ru-ru/training/modules/ai-agent-fundamentals/',
    summary: 'Оркестрация инструментов, память, безопасность агента.',
    encyclopedia: '/encyclopedia/6-ai/6-04-modeli-i-instrumenty/116',
  },
  {
    id: 'copilot-everyday',
    type: 'module',
    section: 'ai',
    level: 'beginner',
    role: 'Бизнес-пользователь',
    product: 'Microsoft Copilot',
    title: 'ИИ для повседневных задач',
    durationMin: 43,
    url: 'https://learn.microsoft.com/ru-ru/training/modules/use-ai-everyday-tasks/',
    summary: 'Промпты в Office и браузере без кода.',
    encyclopedia: '/encyclopedia/6-ai/6-06-primenenie-ii/3',
  },
  {
    id: 'powerbi-start',
    type: 'module',
    section: 'data',
    level: 'beginner',
    role: 'Аналитик данных',
    product: 'Microsoft Power Platform',
    title: 'Начало работы с Power BI',
    durationMin: 21,
    url: 'https://learn.microsoft.com/ru-ru/training/modules/get-started-with-power-bi/',
    summary: 'Импорт, визуализации, публикация отчёта.',
    encyclopedia: '/encyclopedia/3-data-markup/3-11-analiz-dannyh/43',
  },
  {
    id: 'data-analytics-ms',
    type: 'path',
    section: 'data',
    level: 'intermediate',
    role: 'Аналитик данных',
    product: 'Microsoft Power Platform',
    title: 'Аналитика данных Microsoft',
    durationMin: 57,
    url: 'https://learn.microsoft.com/ru-ru/training/paths/data-analytics-microsoft/',
    summary: 'Связка Fabric / Power BI / Synapse на обзорном уровне.',
    encyclopedia: '/encyclopedia/3-data-markup/3-11-analiz-dannyh/43',
  },
  {
    id: 'sc-900-path',
    type: 'path',
    section: 'infra',
    level: 'beginner',
    role: 'Аналитик ИБ',
    product: 'Microsoft Security',
    title: 'Основы безопасности, соответствия и идентичности',
    durationMin: 480,
    url: 'https://learn.microsoft.com/ru-ru/training/paths/describe-security-privacy-compliance-capabilities/',
    summary: 'Zero Trust, Defender, Entra — обзор для SC-900.',
    encyclopedia: '/encyclopedia/8-infra-security/8-07-informatsionnaya-bezopasnost/121',
  },
  {
    id: 'entra-fund',
    type: 'module',
    section: 'system',
    level: 'beginner',
    role: 'Администратор ИБ',
    product: 'Microsoft Entra',
    title: 'Описание служб идентификации Microsoft Entra',
    durationMin: 25,
    url: 'https://learn.microsoft.com/ru-ru/training/modules/describe-basic-identity-services/',
    summary: 'SSO, MFA, B2B, отличие от локального AD.',
    encyclopedia: '/encyclopedia/2-system-network/2-06-sistemnoe-administrirovanie/62',
  },
  {
    id: 'github-actions-intro',
    type: 'module',
    section: 'infra',
    level: 'intermediate',
    role: 'DevOps',
    product: 'GitHub',
    title: 'GitHub Actions — основы CI/CD',
    durationMin: 55,
    url: 'https://learn.microsoft.com/ru-ru/training/modules/github-actions-intro/',
    summary: 'Workflow, secrets, артефакты сборки.',
    encyclopedia: '/encyclopedia/8-infra-security/8-04-devops-ci-cd/3123',
  },
  {
    id: 'playwright-intro',
    type: 'module',
    section: 'project',
    level: 'intermediate',
    role: 'Разработчик',
    product: 'Microsoft Playwright',
    title: 'Автоматизация тестов с Playwright',
    durationMin: 90,
    url: 'https://learn.microsoft.com/ru-ru/training/modules/build-with-playwright/',
    summary: 'E2E в браузере: селекторы, ожидания, отчёты.',
    encyclopedia: '/encyclopedia/8-infra-security/8-04-devops-ci-cd/3123',
  },
  {
    id: 'm365-fund',
    type: 'module',
    section: 'basics',
    level: 'beginner',
    role: 'Бизнес-пользователь',
    product: 'Microsoft 365',
    title: 'Возможности Microsoft 365',
    durationMin: 30,
    url: 'https://learn.microsoft.com/ru-ru/training/modules/m365-fundamentals/',
    summary: 'Teams, Exchange, SharePoint, OneDrive в одной подписке.',
    encyclopedia: '/encyclopedia/1-basics/1-11-soft-ryadovogo-polzovatelya/52',
  },
  {
    id: 'az-900-course',
    type: 'course',
    section: 'infra',
    level: 'beginner',
    role: 'Администратор',
    product: 'Azure',
    title: 'Курс AZ-900: основы Azure',
    durationMin: 480,
    url: 'https://learn.microsoft.com/ru-ru/training/courses/az-900t00/',
    summary: 'Инструкторский формат; для самостоятельного — learning paths выше.',
    encyclopedia: '/encyclopedia/1-basics/1-26-karera-v-it-i-mify/12',
  },
  {
    id: 'pl-900-course',
    type: 'course',
    section: 'data',
    level: 'beginner',
    role: 'Бизнес-пользователь',
    product: 'Microsoft Power Platform',
    title: 'Курс PL-900: Power Platform',
    durationMin: 960,
    url: 'https://learn.microsoft.com/ru-ru/training/courses/pl-900t00/',
    summary: 'Power Apps, Automate, BI — экосистема low-code Microsoft.',
    encyclopedia: '/encyclopedia/8-infra-security/8-02-low-code-no-code/2',
  },
  {
    id: 'dp-900-path',
    type: 'path',
    section: 'data',
    level: 'beginner',
    role: 'Аналитик данных',
    product: 'Azure',
    title: 'Основы данных Azure (DP-900)',
    durationMin: 600,
    url: 'https://learn.microsoft.com/ru-ru/training/paths/prepare-for-dp-900/',
    summary: 'Реляционные и нереляционные данные в облаке — обзор.',
    encyclopedia: '/encyclopedia/3-data-markup/3-07-sql/intro',
  },
  {
    id: 'aspnet-core-intro',
    type: 'path',
    section: 'code',
    level: 'intermediate',
    role: 'Разработчик',
    product: 'ASP.NET Core',
    title: 'Создание веб-приложений ASP.NET Core',
    durationMin: 720,
    url: 'https://learn.microsoft.com/ru-ru/training/paths/aspnet-core/',
    summary: 'После C# и HTTP — MVC/Razor/minimal APIs.',
    encyclopedia: '/encyclopedia/5-languages/5-05-csharp/455',
  },
  {
    id: 'doc-aspnet-core-hub',
    type: 'doc',
    section: 'code',
    level: 'beginner',
    role: 'Разработчик',
    product: 'ASP.NET Core',
    title: 'Документация ASP.NET Core 10 (хаб)',
    durationMin: 0,
    url: 'https://learn.microsoft.com/ru-ru/aspnet/core/?view=aspnetcore-10.0',
    summary: 'Обзор, учебники, API, Blazor, MVC, развёртывание.',
    encyclopedia: '/encyclopedia/5-languages/5-05-csharp/455',
  },
  {
    id: 'doc-aspnet-razor-pages',
    type: 'doc',
    section: 'code',
    level: 'beginner',
    role: 'Разработчик',
    product: 'ASP.NET Core',
    title: 'Серия Razor Pages: RazorPagesMovie',
    durationMin: 180,
    url: 'https://learn.microsoft.com/ru-ru/aspnet/core/tutorials/razor-pages/?view=aspnetcore-10.0',
    summary: '8 частей: PageModel, scaffold, EF, поиск, валидация.',
    encyclopedia: '/encyclopedia/5-languages/5-05-csharp/455',
  },
  {
    id: 'doc-aspnet-mvc-movie',
    type: 'doc',
    section: 'code',
    level: 'beginner',
    role: 'Разработчик',
    product: 'ASP.NET Core',
    title: 'Серия MVC: приложение MvcMovie',
    durationMin: 180,
    url: 'https://learn.microsoft.com/ru-ru/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-10.0&tabs=visual-studio',
    summary: '8 частей: CRUD фильмов, EF, поиск, валидация.',
    encyclopedia: '/encyclopedia/5-languages/5-05-csharp/455',
  },
  {
    id: 'doc-aspnet-mvc-docker-framework',
    type: 'doc',
    section: 'code',
    level: 'intermediate',
    role: 'Разработчик',
    product: 'ASP.NET MVC (.NET Framework)',
    title: 'Legacy MVC в Docker (Windows)',
    durationMin: 45,
    url: 'https://learn.microsoft.com/ru-ru/aspnet/mvc/overview/deployment/docker-aspnetmvc',
    summary: 'Framework 4.8 + IIS; не путать с ASP.NET Core на Linux.',
    encyclopedia: '/encyclopedia/5-languages/5-05-csharp/455',
  },
  {
    id: 'devops-az-400',
    type: 'path',
    section: 'infra',
    level: 'intermediate',
    role: 'DevOps',
    product: 'Azure',
    title: 'DevOps с Azure и GitHub',
    durationMin: 1200,
    url: 'https://learn.microsoft.com/ru-ru/training/paths/az-400-developer/',
    summary: 'Pipelines, IaC, мониторинг релизов.',
    encyclopedia: '/encyclopedia/8-infra-security/8-04-devops-ci-cd/intro',
  },
  {
    id: 'tsql-query-path',
    type: 'path',
    section: 'data',
    level: 'beginner',
    role: 'Разработчик',
    product: 'SQL Server',
    title: 'Запросы на Transact-SQL',
    durationMin: 480,
    url: 'https://learn.microsoft.com/ru-ru/training/paths/get-started-querying-with-transact-sql/',
    summary: 'После базового SQL — T-SQL, JOIN, процедуры, права.',
    encyclopedia: '/encyclopedia/3-data-markup/3-07-sql/882',
  },
  {
    id: 'doc-sql-hub',
    type: 'doc',
    section: 'data',
    level: 'beginner',
    role: 'Разработчик',
    product: 'SQL Server',
    title: 'Документация Microsoft SQL (хаб)',
    durationMin: 0,
    url: 'https://learn.microsoft.com/ru-ru/sql/?view=sql-server-ver17',
    summary: 'SQL Server, Azure SQL, Fabric, миграция, инструменты.',
    encyclopedia: '/encyclopedia/3-data-markup/3-08-upravlenie-rsubd/212',
  },
  {
    id: 'doc-tsql-tutorial',
    type: 'doc',
    section: 'data',
    level: 'beginner',
    role: 'Разработчик',
    product: 'SQL Server',
    title: 'Учебник: Writing Transact-SQL',
    durationMin: 90,
    url: 'https://learn.microsoft.com/ru-ru/sql/t-sql/tutorial-writing-transact-sql-statements?view=sql-server-ver17',
    summary: '3 занятия: объекты БД, разрешения, VIEW и процедуры.',
    encyclopedia: '/encyclopedia/3-data-markup/3-07-sql/882',
  },
  {
    id: 'doc-sql-tools',
    type: 'doc',
    section: 'data',
    level: 'beginner',
    role: 'Администратор',
    product: 'SQL Server',
    title: 'Инструменты SQL Server (SSMS, SSDT)',
    durationMin: 0,
    url: 'https://learn.microsoft.com/ru-ru/sql/tools/overview-sql-tools?view=sql-server-ver17',
    summary: 'SSMS, Azure Data Studio, sqlcmd, SqlPackage, PowerShell.',
    encyclopedia: '/encyclopedia/3-data-markup/3-08-upravlenie-rsubd/212',
  },
  {
    id: 'doc-java-hub',
    type: 'doc',
    section: 'languages',
    level: 'beginner',
    role: 'Разработчик',
    product: 'Java',
    title: 'Разработчики Microsoft для Java (хаб)',
    durationMin: 0,
    url: 'https://learn.microsoft.com/ru-ru/java/',
    summary: 'OpenJDK, VS Code, Azure SDK, App Service, GitHub Actions.',
    encyclopedia: '/encyclopedia/5-languages/5-03-java/294',
  },
  {
    id: 'doc-java-openjdk-download',
    type: 'doc',
    section: 'languages',
    level: 'beginner',
    role: 'Разработчик',
    product: 'OpenJDK',
    title: 'Microsoft Build of OpenJDK — скачивание',
    durationMin: 0,
    url: 'https://learn.microsoft.com/ru-ru/java/openjdk/download',
    summary: 'LTS-сборки JDK для Windows, Linux, macOS.',
    encyclopedia: '/encyclopedia/5-languages/5-03-java/294',
  },
  {
    id: 'doc-java-openjdk-install',
    type: 'doc',
    section: 'languages',
    level: 'beginner',
    role: 'Разработчик',
    product: 'OpenJDK',
    title: 'Установка Microsoft Build of OpenJDK',
    durationMin: 0,
    url: 'https://learn.microsoft.com/ru-ru/java/openjdk/install?tabs=exe%2Chomebrew%2Cubuntu',
    summary: 'exe, Homebrew, Ubuntu — JAVA_HOME и проверка java -version.',
    encyclopedia: '/encyclopedia/5-languages/5-03-java/13',
  },
  {
    id: 'doc-vscode-java',
    type: 'doc',
    section: 'code',
    level: 'beginner',
    role: 'Разработчик',
    product: 'Visual Studio Code',
    title: 'Getting Started with Java in VS Code',
    durationMin: 0,
    url: 'https://code.visualstudio.com/docs/java/java-tutorial',
    summary: 'Coding Pack, отладка, Maven и Gradle.',
    encyclopedia: '/encyclopedia/5-languages/5-03-java/294',
  },
  {
    id: 'doc-azure-java-sdk',
    type: 'doc',
    section: 'languages',
    level: 'intermediate',
    role: 'Разработчик',
    product: 'Azure',
    title: 'Пакеты SDK Azure для Java',
    durationMin: 0,
    url: 'https://learn.microsoft.com/ru-ru/azure/developer/java/sdk/overview',
    summary: 'Клиенты Storage, Key Vault, Service Bus и др.',
    encyclopedia: '/encyclopedia/5-languages/5-03-java/294',
  },
  {
    id: 'doc-azure-java-appservice',
    type: 'doc',
    section: 'infra',
    level: 'beginner',
    role: 'Разработчик',
    product: 'Azure App Service',
    title: 'Быстрый старт: Java в App Service',
    durationMin: 0,
    url: 'https://learn.microsoft.com/ru-ru/azure/app-service/quickstart-java?tabs=springboot&pivots=java-javase',
    summary: 'Spring Boot или Java SE — развёртывание в Azure.',
    encyclopedia: '/encyclopedia/5-languages/5-03-java/271',
  },
  {
    id: 'doc-azure-java-ee',
    type: 'doc',
    section: 'languages',
    level: 'intermediate',
    role: 'Разработчик',
    product: 'Jakarta EE',
    title: 'Java EE, Jakarta EE и MicroProfile в Azure',
    durationMin: 0,
    url: 'https://learn.microsoft.com/ru-ru/azure/developer/java/ee/',
    summary: 'WildFly, Liberty, Payara в контейнерах и Kubernetes.',
    encyclopedia: '/encyclopedia/5-languages/5-03-java/110',
  },
  {
    id: 'doc-gh-setup-java',
    type: 'doc',
    section: 'infra',
    level: 'beginner',
    role: 'DevOps',
    product: 'GitHub Actions',
    title: 'setup-java-jdk (GitHub Actions)',
    durationMin: 0,
    url: 'https://github.com/marketplace/actions/setup-java-jdk',
    summary: 'JDK microsoft/temurin, кэш Maven/Gradle в CI.',
    encyclopedia: '/encyclopedia/5-languages/5-03-java/12',
  },
];

export const TYPE_LABELS = {
  path: 'Схема обучения',
  module: 'Модуль',
  course: 'Курс',
  doc: 'Документация',
};

export function formatDuration(minutes) {
  if (!minutes) return 'Справочник';
  if (minutes < 60) return `${minutes} мин`;
  const h = Math.floor(minutes / 60);
  const m = minutes % 60;
  return m ? `${h} ч ${m} мин` : `${h} ч`;
}
