export const steamHeader = (appId) =>
  `https://cdn.cloudflare.steamstatic.com/steam/apps/${appId}/header.jpg`;

export const SALE_NAME = 'Летняя распродажа Steam 2026';
export const CART_LIMIT = 12;
export const STARTING_WALLET = 500;
export const STORAGE_KEY = 'itu-steam-sale-simulator';

export const REVIEW_LABELS = {
  overwhelmingly_positive: 'Крайне положительные',
  very_positive: 'Очень положительные',
  positive: 'В основном положительные',
  mixed: 'Смешанные',
};

export const STEAM_GAMES = [
  {
    id: 1,
    appId: 1245620,
    title: 'ELDEN RING',
    tags: ['Souls-like', 'Open World', 'RPG'],
    originalPrice: 59.99,
    salePrice: 35.99,
    discount: 40,
    reviewScore: 'overwhelmingly_positive',
  },
  {
    id: 2,
    appId: 1091500,
    title: 'Cyberpunk 2077',
    tags: ['Cyberpunk', 'Open World', 'RPG'],
    originalPrice: 59.99,
    salePrice: 29.99,
    discount: 50,
    reviewScore: 'very_positive',
  },
  {
    id: 3,
    appId: 1174180,
    title: 'Red Dead Redemption 2',
    tags: ['Open World', 'Western', 'Story Rich'],
    originalPrice: 59.99,
    salePrice: 19.79,
    discount: 67,
    reviewScore: 'overwhelmingly_positive',
  },
  {
    id: 4,
    appId: 1145360,
    title: 'Hades',
    tags: ['Roguelike', 'Indie', 'Action'],
    originalPrice: 24.99,
    salePrice: 12.49,
    discount: 50,
    reviewScore: 'overwhelmingly_positive',
  },
  {
    id: 5,
    appId: 413150,
    title: 'Stardew Valley',
    tags: ['Farming', 'Indie', 'Relaxing'],
    originalPrice: 14.99,
    salePrice: 7.49,
    discount: 50,
    reviewScore: 'overwhelmingly_positive',
  },
  {
    id: 6,
    appId: 367520,
    title: 'Hollow Knight',
    tags: ['Metroidvania', 'Indie', 'Difficult'],
    originalPrice: 14.99,
    salePrice: 7.49,
    discount: 50,
    reviewScore: 'overwhelmingly_positive',
  },
  {
    id: 7,
    appId: 1086940,
    title: 'Baldur\'s Gate 3',
    tags: ['RPG', 'Story Rich', 'Turn-Based'],
    originalPrice: 59.99,
    salePrice: 47.99,
    discount: 20,
    reviewScore: 'overwhelmingly_positive',
  },
  {
    id: 8,
    appId: 1599340,
    title: 'Lies of P',
    tags: ['Souls-like', 'Action', 'Dark Fantasy'],
    originalPrice: 59.99,
    salePrice: 35.99,
    discount: 40,
    reviewScore: 'very_positive',
  },
  {
    id: 9,
    appId: 1817070,
    title: 'Spider-Man Remastered',
    tags: ['Action', 'Superhero', 'Open World'],
    originalPrice: 59.99,
    salePrice: 35.99,
    discount: 40,
    reviewScore: 'overwhelmingly_positive',
  },
  {
    id: 10,
    appId: 620,
    title: 'Portal 2',
    tags: ['Puzzle', 'Co-op', 'Classic'],
    originalPrice: 9.99,
    salePrice: 1.99,
    discount: 80,
    reviewScore: 'overwhelmingly_positive',
  },
  {
    id: 11,
    appId: 105600,
    title: 'Terraria',
    tags: ['Sandbox', 'Survival', 'Indie'],
    originalPrice: 9.99,
    salePrice: 4.99,
    discount: 50,
    reviewScore: 'overwhelmingly_positive',
  },
  {
    id: 12,
    appId: 252950,
    title: 'Rocket League',
    tags: ['Sports', 'Multiplayer', 'Free to Play'],
    originalPrice: 0,
    salePrice: 0,
    discount: 0,
    reviewScore: 'very_positive',
  },
  {
    id: 13,
    appId: 1172470,
    title: 'Apex Legends',
    tags: ['Battle Royale', 'Free to Play', 'FPS'],
    originalPrice: 0,
    salePrice: 0,
    discount: 0,
    reviewScore: 'mixed',
  },
  {
    id: 14,
    appId: 271590,
    title: 'Grand Theft Auto V',
    tags: ['Open World', 'Action', 'Multiplayer'],
    originalPrice: 29.99,
    salePrice: 14.99,
    discount: 50,
    reviewScore: 'very_positive',
  },
  {
    id: 15,
    appId: 892970,
    title: 'Valheim',
    tags: ['Survival', 'Co-op', 'Viking'],
    originalPrice: 19.99,
    salePrice: 9.99,
    discount: 50,
    reviewScore: 'very_positive',
  },
];

export const DEFAULT_STATE = {
  cart: [],
  wishlist: [],
  library: [],
  wallet: STARTING_WALLET,
  stats: {
    totalSpent: 0,
    gamesPurchased: 0,
    cartFillCount: 0,
    wishlistAdds: 0,
    impulseBuys: 0,
  },
};
