/** Данные для интерактивов раздела tools/network */

export const BROWSER_ENGINE_FILTERS = [
  {id: 'all', label: 'Все'},
  {id: 'blink', label: 'Blink (Chromium)'},
  {id: 'gecko', label: 'Gecko'},
  {id: 'webkit', label: 'WebKit'},
];

export const BROWSERS = [
  {
    id: 'chrome',
    name: 'Google Chrome',
    engine: 'blink',
    os: 'Win, macOS, Linux, Android',
    focus: 'Скорость, экосистема Google, PWA',
    install: 'google.com/chrome',
    free: 'free',
  },
  {
    id: 'firefox',
    name: 'Mozilla Firefox',
    engine: 'gecko',
    os: 'Кроссплатформа',
    focus: 'Приватность, открытый код, контейнеры',
    install: 'mozilla.org/firefox',
    free: 'free',
  },
  {
    id: 'edge',
    name: 'Microsoft Edge',
    engine: 'blink',
    os: 'Win (встроен), macOS, Linux',
    focus: 'Интеграция Windows, IE mode, Entra ID',
    install: 'microsoft.com/edge',
    free: 'free',
  },
  {
    id: 'brave',
    name: 'Brave',
    engine: 'blink',
    os: 'Кроссплатформа',
    focus: 'Блокировка рекламы и трекеров по умолчанию',
    install: 'brave.com',
    free: 'free',
  },
  {
    id: 'vivaldi',
    name: 'Vivaldi',
    engine: 'blink',
    os: 'Кроссплатформа',
    focus: 'Настройка UI, веб-панели, заметки',
    install: 'vivaldi.com',
    free: 'free',
  },
  {
    id: 'safari',
    name: 'Safari',
    engine: 'webkit',
    os: 'macOS, iOS',
    focus: 'Энергоэффективность, экосистема Apple',
    install: 'App Store / системные обновления',
    free: 'free',
  },
  {
    id: 'tor',
    name: 'Tor Browser',
    engine: 'gecko',
    os: 'Win, macOS, Linux',
    focus: 'Анонимность через сеть Tor',
    install: 'torproject.org/download',
    free: 'free',
  },
  {
    id: 'librewolf',
    name: 'LibreWolf',
    engine: 'gecko',
    os: 'Win, macOS, Linux',
    focus: 'Firefox без телеметрии, жёсткая приватность',
    install: 'librewolf.net',
    free: 'free',
  },
  {
    id: 'ungoogled',
    name: 'Ungoogled Chromium',
    engine: 'blink',
    os: 'Win, macOS, Linux',
    focus: 'Chromium без сервисов Google',
    install: 'github.com/ungoogled-software',
    free: 'free',
  },
  {
    id: 'yandex',
    name: 'Yandex Browser',
    engine: 'blink',
    os: 'Win, macOS, Linux, Android',
    focus: 'Турбо, защита от фишинга, сервисы Яндекса',
    install: 'browser.yandex.ru',
    free: 'free',
  },
];

export const MESSENGER_FILTERS = [
  {id: 'all', label: 'Все'},
  {id: 'personal', label: 'Личные'},
  {id: 'team', label: 'Команды'},
  {id: 'secure', label: 'Приватность'},
  {id: 'self', label: 'Self-host'},
];

export const MESSENGERS = [
  {
    id: 'telegram',
    name: 'Telegram',
    cat: 'personal',
    os: 'Кроссплатформа',
    e2ee: 'Секретные чаты; облако по умолчанию',
    note: 'Каналы, боты, файлы до 2 ГБ',
    install: 'telegram.org / desktop.telegram.org',
  },
  {
    id: 'signal',
    name: 'Signal',
    cat: 'secure',
    os: 'Кроссплатформа',
    e2ee: 'E2EE по умолчанию',
    note: 'Минимальная телеметрия, open-source',
    install: 'signal.org',
  },
  {
    id: 'slack',
    name: 'Slack',
    cat: 'team',
    os: 'Кроссплатформа',
    e2ee: 'Шифрование в транзите; не E2EE для workspace',
    note: 'Интеграции GitHub, Jira, поиск по истории',
    install: 'slack.com/downloads',
  },
  {
    id: 'teams',
    name: 'Microsoft Teams',
    cat: 'team',
    os: 'Win, macOS, Linux, мобильные',
    e2ee: 'Зависит от политики M365',
    note: 'Видео, SharePoint, Outlook',
    install: 'microsoft.com/microsoft-teams',
  },
  {
    id: 'discord',
    name: 'Discord',
    cat: 'personal',
    os: 'Кроссплатформа',
    e2ee: 'Нет E2EE в личных DM (по состоянию на 2026)',
    note: 'Голосовые каналы, боты, сообщества',
    install: 'discord.com/download',
  },
  {
    id: 'element',
    name: 'Element (Matrix)',
    cat: 'self',
    os: 'Кроссплатформа',
    e2ee: 'E2EE, федерация серверов',
    note: 'Мосты IRC/Slack, свой homeserver',
    install: 'element.io/get-element',
  },
  {
    id: 'mattermost',
    name: 'Mattermost',
    cat: 'self',
    os: 'Кроссплатформа',
    e2ee: 'TLS; контроль данных на сервере',
    note: 'Альтернатива Slack, open-source CE',
    install: 'mattermost.com/download',
  },
  {
    id: 'zulip',
    name: 'Zulip',
    cat: 'team',
    os: 'Кроссплатформа',
    e2ee: 'TLS; self-host',
    note: 'Потоки и топики вместо ленты',
    install: 'zulip.com/apps',
  },
  {
    id: 'whatsapp',
    name: 'WhatsApp',
    cat: 'personal',
    os: 'Мобильные + desktop через телефон',
    e2ee: 'E2EE (Signal Protocol)',
    note: 'Привязка к номеру, web/desktop',
    install: 'whatsapp.com/download',
  },
  {
    id: 'session',
    name: 'Session',
    cat: 'secure',
    os: 'Мобильные, desktop (beta)',
    e2ee: 'Децентрализованная сеть, без номера',
    note: 'Анонимные идентификаторы',
    install: 'getsession.org',
  },
];

export const VIDEO_FILTERS = [
  {id: 'all', label: 'Все'},
  {id: 'oss', label: 'Open-source'},
  {id: 'cloud', label: 'Облако'},
  {id: 'stream', label: 'Стрим / запись'},
];

export const VIDEO_TOOLS = [
  {
    id: 'jitsi',
    name: 'Jitsi Meet',
    cat: 'oss',
    os: 'Браузер, self-host',
    cap: 'WebRTC, без клиента, Docker',
    install: 'jitsi.org',
  },
  {
    id: 'bbb',
    name: 'BigBlueButton',
    cat: 'oss',
    os: 'Self-host (Ubuntu)',
    cap: 'Вебинары, whiteboard, breakout rooms',
    install: 'bigbluebutton.org',
  },
  {
    id: 'zoom',
    name: 'Zoom',
    cat: 'cloud',
    os: 'Кроссплатформа',
    cap: 'До 1000 участников (платно), запись',
    install: 'zoom.us/download',
  },
  {
    id: 'teams',
    name: 'Microsoft Teams',
    cat: 'cloud',
    os: 'Кроссплатформа',
    cap: 'M365, совместное редактирование',
    install: 'teams.microsoft.com',
  },
  {
    id: 'meet',
    name: 'Google Meet',
    cat: 'cloud',
    os: 'Браузер, мобильные',
    cap: 'Calendar, live captions',
    install: 'meet.google.com',
  },
  {
    id: 'obs',
    name: 'OBS Studio',
    cat: 'stream',
    os: 'Кроссплатформа',
    cap: 'Запись экрана, RTMP, виртуальная камера',
    install: 'obsproject.com',
  },
  {
    id: 'livekit',
    name: 'LiveKit',
    cat: 'oss',
    os: 'Self-host / cloud',
    cap: 'WebRTC SFU для кастомных приложений',
    install: 'livekit.io',
  },
  {
    id: 'whereby',
    name: 'Whereby',
    cat: 'cloud',
    os: 'Браузер',
    cap: 'Комната по URL, малые команды',
    install: 'whereby.com',
  },
];

export const PROTOCOL_LAYERS = [
  {n: 7, name: 'Прикладной', examples: ['HTTP', 'DNS', 'SMTP', 'MQTT']},
  {n: 6, name: 'Представления', examples: ['TLS', 'JSON', 'Protobuf']},
  {n: 5, name: 'Сеансовый', examples: ['TLS session', 'RPC']},
  {n: 4, name: 'Транспортный', examples: ['TCP', 'UDP', 'QUIC']},
  {n: 3, name: 'Сетевой', examples: ['IP', 'ICMP']},
  {n: 2, name: 'Канальный', examples: ['Ethernet', 'ARP', 'Wi‑Fi']},
  {n: 1, name: 'Физический', examples: ['Кабель', 'радио']},
];

export const PROTOCOLS = [
  {
    id: 'http',
    name: 'HTTP/HTTPS',
    layer: 7,
    role: 'Веб-страницы и API; HTTPS = HTTP + TLS',
    tools: 'Браузер, curl, nginx',
  },
  {
    id: 'dns',
    name: 'DNS',
    layer: 7,
    role: 'Имя домена → IP-адрес',
    tools: 'dig, BIND, Unbound',
  },
  {
    id: 'tcp',
    name: 'TCP / UDP',
    layer: 4,
    role: 'Надёжная vs быстрая доставка датаграмм',
    tools: 'netstat, Wireshark',
  },
  {
    id: 'quic',
    name: 'QUIC / HTTP/3',
    layer: 4,
    role: 'Меньше задержка установки соединения',
    tools: 'Chrome, Cloudflare, Caddy',
  },
  {
    id: 'tls',
    name: 'TLS',
    layer: 6,
    role: 'Шифрование и аутентификация канала',
    tools: 'OpenSSL, certbot',
  },
  {
    id: 'smtp',
    name: 'SMTP / IMAP / POP3',
    layer: 7,
    role: 'Отправка и получение почты',
    tools: 'Thunderbird, Postfix',
  },
  {
    id: 'ftp',
    name: 'FTP / SFTP',
    layer: 7,
    role: 'Передача файлов (SFTP поверх SSH)',
    tools: 'FileZilla, WinSCP, scp',
  },
  {
    id: 'ssh',
    name: 'SSH',
    layer: 7,
    role: 'Удалённая shell и туннели',
    tools: 'OpenSSH, PuTTY',
  },
  {
    id: 'websocket',
    name: 'WebSocket',
    layer: 7,
    role: 'Двунаправленный канал поверх TCP',
    tools: 'Socket.io, ws (Node)',
  },
  {
    id: 'mqtt',
    name: 'MQTT',
    layer: 7,
    role: 'Pub/sub для IoT',
    tools: 'Mosquitto, EMQX',
  },
  {
    id: 'webrtc',
    name: 'WebRTC',
    layer: 7,
    role: 'P2P аудио/видео в браузере',
    tools: 'Jitsi, Meet, STUN/TURN',
  },
  {
    id: 'snmp',
    name: 'SNMP',
    layer: 7,
    role: 'Мониторинг сетевых устройств',
    tools: 'Zabbix, LibreNMS',
  },
];
